### ISSUE TITLE
Can activate IME, but not switch input method

### ISSUE THREAD

**Issue by Socialdarwinist** [ddnet/ddnet#1008]
There have been some fixes for the IMEs the last year that have helped a lot, ref #683 and f627a72ebb7ad325b1fbba49d4988a42d0ca5c6e. So the DDNet client does now understand if I press the Ctrl+Space combination to activate the Fcitx method. However I have a second combination Ctrl+Shift to switch between input methods in Fcitx’s active state, i.e. if I use more than two input methods, and switching between the non-default ones does not work.

If in another application, say my webbrowser, I have written something in Hebrew and I then activate Fcitx with Ctrl+Space, the chosen layout will be Hebrew until I change it outside the DDNet client to be something else like Russian that I write in Teeworlds because in the DDNet client my second combination does not work.

**Comment by PathosEthosLogos** [comment]
Probably related to #1030

**Comment by yangfl** [comment]
Alt+L_Shift (for ibus) does not work as well

**Comment by def-** [comment]
This is a bit hard for me to fix since I don't use these IMEs and don't know much about how they work and how to test this properly. Anyone feeling up to the task? First step would be to figure out what change broke #1030 and #1008 or if they have been broken forever.

**Comment by yangfl** [comment]
IBus used to work in 10.6.4, but after one day (maybe an update), it broke. Now even not work with 10.0.3.

**Comment by PathosEthosLogos** [comment]
I have a slight different case. Note that I tested this on Windows 10.

Japanese: does not work at all :(

Korean: works, though with one minor behaviour problem, but I don't think Korean typists would have much of a problem. For those of interest, it's kind of hard to describe the behaviour, but essentially, typing `티월즈 [enter]` would result in "티월" while "즈" would be left over since it is still in input mode, so to speak. In chat, only "티월" would show, but in f1 console, it would run *two* commands with a single [enter] key press (not that Korean commands exist). The solution for me is just to press space before pressing enter.
