### ISSUE TITLE
Low fps when OpenGL enabled in 11.0.2

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#1010]
I notice lot fewer fps than when i have the opengl feature enabled.
I think this didn't happen in previous versions that supported opengl

These are my settings:
![](https://image.prntscr.com/image/MoiMaUpVT-WC_PQ3WqEcZg.png)

GPU is a amd r9 390 8gb vram

**Comment by def-** [comment]
@Jupeyy Any ideas?

**Comment by Jupeyy** [comment]
preinit VBO iGPUs only, integraded graphic cards are GPUs included in Intels CPUs.. probably but not sure, always without VRAM, that's why this option helps, since it allows just storing everything in the system memory instead of VRAM(that doesnt exists in this case).


on short: disable it, since you have a dedicated GPU

**Comment by Ryozuki** [comment]
Yep runs perfectly without that, maybe u should change iGPU to integrated GPU.
Or maybe its just me that i'm dumb and didn't know iGPU meant that.
