### ISSUE TITLE
Creating a demo after-the-fact

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#1040]
From DDNet discord, #general:
>[1:27 PM] Michel: Is it possible to add a shadowplay like feature to, teeworlds? So you can type in a command in console and it saves like the last 30 seconds in demos?
>[1:33 PM] heinrich5991: ah, that would be very nice :)
>[1:33 PM] heinrich5991: I'll create an issue

**Comment by def-** [comment]
Just Enable autorecorder and set maximum demos to how much back you want to go? marker can be used to mark important positions.

**Comment by ChillerDragon** [comment]
This would be a great feature. Since stopping Auto Demos manually is broken. And the demomarker has a offset and it is a lot of work to sort all demos. I don't understand how deleting demos should help. It is also possible to sort by date and have a look at the last x demos. But unlimited demos allow you to look up old stuff (which was very usefull for me already).

Creating a cutted demo of the last x seconds via bind would save some people a lot of time. It would be cool to have the length dynamic by using a config var.

**Comment by Learath2** [comment]
#1748 closes this
