### ISSUE TITLE
Bors

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#1099]
It's way too slow, and @def- seems to have some trouble getting it working at all. Do we really want it?

**Comment by def-** [comment]
Or I use it wrong?

**Comment by ChillerDragon** [comment]
i like bors c:
since he stopped spamming in discord he became a close friend.
I didn't see any problems so far. He is even save agianst pushing commits after he got activated (my test canceled the bors process so this was one case deen borsed and it failed but it was a good fail i guess)

**Comment by heinrich5991** [comment]
You (@Learath2 and @def-) *should* be able to access the bors instance at https://app.bors.tech/ after a GitHub login, there seem to have been some troubles in the logs ("History").

bors exists so that ideally, no broken build gets merged into master. I like the concept and I think we should continue using it as long as it's not broken (as it apparently was when I was on vacation ._.).
