### ISSUE TITLE
windows 10 / opengl3 / ddnet 11.1.4 => display bug + crash on exit

### ISSUE THREAD

**Issue by daverck** [ddnet/ddnet#1105]
If I disable gfx_enable_texture_unit_optimization I don't have a crash while exiting.

might be related to #1083 #1028

![crash_exit](https://user-images.githubusercontent.com/7854728/38456802-e560e464-3a88-11e8-8bb4-c2e2e5baf5cd.PNG)
![display_bug](https://user-images.githubusercontent.com/7854728/38456807-ebf3b676-3a88-11e8-89b9-d456068e11e3.PNG)

**Comment by Jupeyy** [comment]
Update, downgrade your GPU driver, the chance it's not small that it's its fault

**Comment by daverck** [comment]
For what it's worth I tested opengl3/4 with this soft ([http://www.ozone3d.net/gpu_caps_viewer/]) successfully.

I don't want to mess with my drivers :3

Here is a link about my hardware configuration : [https://www.driverscloud.com/en/printconfiguration/52079447-36-1/graphics-card]

My graphic card is a radeon gtx 5800

**Comment by Jupeyy** [comment]
that's only a caps viewer, that doesn't fix driver bugs, nor does it show any.

the Intel HD graphics won't work either.

I can't help you here, sorry. 
You can switch to linux, if you don't any windows specific things.
There was a time, where OpenGL was really bad with AMD, I see a lot of troubles with older AMD hardware.

**Comment by Jupeyy** [comment]
It is a driver issue, i even know how to fix it, but it would create overhead for all other GPUs, thus i'm not fixing it.
The issue is that your driver can't handle vertex array attributes, that are uploaded as unsigned byte with the float function.
That basically means, the shader gets the value as float, but internally it's stored as byte, resulting in smaller RAM usage, that is an problem because it wouldn't only affect the proper size, but also the upload alignment of the other attributes, which would require respecting this alignment, or changing all value to floats, making it even bigger.

The whole sense of GPUs is having the advantage of parallelisation, less memory transfer(therefore a convert from byte to float) is just worth it.

**Comment by daverck** [comment]
would it be easy to disable opengl3 option for old amd card that doesn't support it properly ?

**Comment by def-** [comment]
opengl3 is already disabled by default, isn't it?

**Comment by daverck** [comment]
i meant to hide it.
enabling it by default would be nice.

**Comment by PathosEthosLogos** [comment]
>It is a driver issue, i even know how to fix it, but it would create overhead for all other GPUs, thus i'm not fixing it.
Is this the stance from the DDNet devs in general?

I guess this thread can be closed now, right?

**Comment by def-** [comment]
Let's keep OpenGL3 as experimental forever since it seems too hard to fix the bugs with all combinations of GPUs.
