### ISSUE TITLE
Installing DDNet with 'make install'

### ISSUE THREAD

**Issue by rffontenelle** [ddnet/ddnet#1269]
I would like to use a 'make install'-like in my [(Arch Linux) AUR ddnet package](https://aur.archlinux.org/packages/ddnet/) for installing files to the package. Currently I'm doing the installation manually.

So far I found two ways of installing via makefile/cmake:

1- `make install DESTDIR=path/to/pkg/` or `cmake -P cmake_install.cmake` (without providing `-DCOMPONENT=portable`) will install only the client and server binary.

2- `DESTDIR=path/to/pkg/ cmake -DCOMPONENT=portable -P cmake_install.cmake` will install all files ready-to-go from a portable folder, as seen in the tar.xz files in the Download page of the website

However none of them allow me to install all files to the proper directories, like binaries in _prefix_/bin, the data/ stuff in _prefix_/_datadir_ (e.g. /usr/share/data/ddnet), etc.

Did I miss anything? Case not, could this be implemented to simplify install instructions?

**Comment by def-** [comment]
Might be related: https://github.com/ddnet/ddnet/pull/1265

**Comment by rffontenelle** [comment]
6c90aadc is an awesome progress. Can we have tools installation, if `make tools` is used?

Also, I notice some tools, like dilate, are installed with DDNet and DDNet-Server. In my package I put them in different folders. Is in the best interest of DDNet developers to keep them in /usr/bin together?

**Comment by heinrich5991** [comment]
There seem to be some silly CMake limitations around that issue. :/

If you want to be able to "install" something, it has to be built by default. This would mean that every developer would need to rebuild all the tools every time something in src/base or src/engine changed. This looks undesirable to me.

One option would be to make a config option, to be provided to the initial CMake command line, which says whether this is a development build (only build client and server by default) or a release build (build everything by default). An interesting question is whether you'd want to have the default be "developer" or "packager". The advantage of "developer" is that there are probably more people checking out the code to hack on it, the advantage of "packager" is that we don't break too far from the usual "configure; make; install" scheme that people usually have in mind (it's why we build for "Release" instead of "Debug" by default).

I'm currently leaning towards making a DEV or DEVELOP or so variable that can be provided to *not* build everything by default.

Thoughts..?

[Installing only one target (and its dependencies) out of a complex project with cmake (open to better solutions) – Stack Overflow](https://stackoverflow.com/a/17201375)
[EXCLUDE_FROM_ALL – CMake documentation](https://cmake.org/cmake/help/v3.12/prop_tgt/EXCLUDE_FROM_ALL.html?highlight=undefined%20behavior)

**Comment by def-** [comment]
Couldn't we just have multiple build targets? Default builds Client + Server, but you can also specifiy targets [c]client[/c], [c]server[/c], [c]tools[/c] and [c]all[/c] (client + server + tools)
