### ISSUE TITLE
Go through the vanilla 0.7 changelog and pick useful changes for us

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1403]
https://www.teeworlds.com/forum/viewtopic.php?id=12606

On a quick look I like:
- composed binds (ctrl+, shift+, alt+)
- master server list cache (in case the masters are unreachable)
- make client launchable from the browser given a special link (#1478)
- mapres update (higher resolution, fixes...)

**Comment by fokkonaut** [comment]
mapres update... makes every map ugly?...

**Comment by def-** [comment]
Haven't seem them yet. Got an example?

**Comment by def-** [comment]
Ehm, we have 64 player support already, just need to port it to other game types, but I guess there isn't much interest in them.

**Comment by def-** [comment]
https://github.com/teeworlds/teeworlds/pull/1589/files
Looks quite complex

**Comment by PathosEthosLogos** [comment]
> https://github.com/teeworlds/teeworlds/pull/1589/files
> Looks quite complex
Interesting, they call for shift ctrl alt keys specifically, not a reference (like a pointer) to those keys. I'm not sure if that's how it's written for other games, but this means that compound binds wouldn't be super customisable. I guess it makes sense, but this means that a key combination like z + g wouldn't be possible, only ctrl + g. Not a big issue at all though.


>     * master server list cache (in case the masters are unreachable)
See #1162 
I think we should separate the four bullet points in this topic into four separate issues (or three since there's already issue 1162).

Also, can you make an official statement on DDNet vs. 0.7 in the forums @def- ? My guess is that DDNet won't be going over to 0.7 and stay on 0.6.3. I think people are in this ambiguous state of whether DDNet will be going over to 0.7 or not. Even if it's obvious that it will or not, please make the statement because it's not obvious to everyone!

So since it will be staying on 0.6.3, why not just get rid of these numbers and just keep DDNet version now? Maybe just write on the documentation that DDNet came out of 0.6.3.

**Comment by def-** [comment]
> My guess is that DDNet won't be going over to 0.7 and stay on 0.6.3.

Does 0.7 have any physics changes? That's the main issue for DDNet.
