### ISSUE TITLE
Map Editor bugs and crashes

### ISSUE THREAD

**Issue by Cellegen** [ddnet/ddnet#1425]
So the Map Editor in the 11.6 version or DDNet Client is more likely broken at this point:

-Doing a selected hotkey line (Shift + Right Click into the "Game" folder or some objects) can produce instant crash with losing all of your progress on it. (what is annoying in the way that it doesn't autosave)
-The mouse ui is not perfectly functionable with the settings that i set on. (sometimes faster than the set setting; makes it difficult to aim to the little edit dots)
-The rendering with multiple selecting can cause some issues. (The video is linked here to see what im actually talking about)

[2019-01-09 07-54-19.zip](https://github.com/ddnet/ddnet/files/2739732/2019-01-09.07-54-19.zip)

I didn't see any more issues than that. And i hope that won't more bugs be showen.

**Comment by def-** [comment]
Fixed the first one.

@timakro Any idea for the other ones?

**Comment by Cellegen** [comment]
@def- now i can't take screenshots in 11.7 lol

**Comment by def-** [comment]
Sounds unrelated to this bug.

**Comment by timakro** [comment]
I can't reproduce the other two issues.

I made a [fix](https://github.com/ddnet/ddnet/commit/8da9a5f9f1e9ca76cea99b6377f25d12f3ffbc51) to the mouse ui a while ago where the dots you dragged would sometimes fall behind the mouse. With the fix the dots always stay exactly under the mouse. The dots are always placed in exact relation to the mouse so if you grab the dot on its top left corner as soon as you move the mouse you will notice the quad being teleported slightly so that the dot is centered on the mouse. Could that possibly be your issue?

I tried creating multiple quads and also selecting the red corner dots as well but couldn't reproduce the issue in the video. Very strange one.

**Comment by Cellegen** [comment]
Maybe when i updated my client, it got corrupted at that point where that does that.
Other that that, that should be it.

**Comment by Cellegen** [comment]
@def- I found a bug related to automap.
When i have a tileset with an automap, placing it outside of the white box makes my client unresponsive and crashes itself. (Video is attached here for better understanding)

[2019-01-10 15-16-19.zip](https://github.com/ddnet/ddnet/files/2745684/2019-01-10.15-16-19.zip)

**Comment by def-** [comment]
Thanks, can reproduce, will fix now.

**Comment by def-** [comment]
So the only remaining issue here is "mouse moves too fast in editor"?

**Comment by def-** [comment]
which already has a bug: https://github.com/ddnet/ddnet/issues/1367
