### ISSUE TITLE
Crash when copying multiple layers to another map

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1452]
As reported here: https://forum.ddnet.tw/viewtopic.php?t=6747
> If u trying copy all game tiles (swither, tele,game itc ) with hold shift, then load map , then if u trying paste switch and speedup,client will be crashed, if u trying paste tele it is just no pasted.
ps ddclient 11.7.2

@bojidar-bg Could you take a look?

**Comment by trikiman** [comment]
What about tele,switch itc ? this not copy at other map.

**Comment by trikiman** [comment]
i cant paste map here. take it from https://forum.ddnet.tw/viewtopic.php?f=45&t=6747

**Comment by def-** [comment]
@bojidar-bg ^

**Comment by bojidar-bg** [comment]
Well, not sure how to fix it exactly. If someone wants to have a look, feel free.

Also, if someone writes a slightly more descriptive explanation of what happens and what is expected to happen, I might give it another try.

**Comment by trikiman** [comment]
> Well, not sure how to fix it exactly. If someone wants to have a look, feel free.
> 
> Also, if someone writes a slightly more descriptive explanation (with proper grammar, either in English or in any other language) of what happens and what is expected to happen, I might give it another try.

So, if u trying copy tele,switch itc from ethereal.map to tp.map it is no paste. 
download map from here https://forum.ddnet.tw/viewtopic.php?f=45&t=6747 .
if u copy from tp.map to tp.map(other version) it is ok.

**Comment by bojidar-bg** [comment]
@trikiman Nope can't confirm. Maybe because you aren't selecting the same layers in the same order?
I selected Game, then Front, then Tele, etc., then did selected the layers in the same order on the other map. It worked.
If you select them in some other order, it would reject pasting though. It might be possible to make it fix the order by itself, but that would be somewhat tricky.

<details>
<summary>(click to expand) last message with fixed grammar</summary>
<p>

So, if **you** **try to** copy tele, switch, **etc.** from `ethereal.map` to `tp.map`, it **does not** paste *anything*.
You **can** download **the maps** from here: https://forum.ddnet.tw/viewtopic.php?f=45&t=6747.
If **you** copy from `tp.map` to *another version of* `tp.map`, it is ok.

</p>
</details>

**Comment by Robyt3** [comment]
Should not happen anymore because we clear saved brushes when loading another map.
