### ISSUE TITLE
cl_predict_freeze/Stopper bobbing

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1726]
**cl_predict_freeze**
#1701
cl_predict_freeze should be set to ~~2~~ by default since moving your tee in freeze and seeing if your tee is at the wall or if left/right movement is locked is crucial information.
~~(i say 2 since for me personally the screen is not as shaky as on 0)~~

**Stopper bobbing**

Strong hook:
![Strong](https://user-images.githubusercontent.com/47721445/57585719-3a41b780-74ec-11e9-9ae3-417c80964c96.gif)
Weak hook:
![Weak](https://user-images.githubusercontent.com/47721445/57585720-3f9f0200-74ec-11e9-96a1-ea0cb1082456.gif)
Would it be possible to 'fix' this? @trml

**Comment by fokkonaut** [comment]
i would like freeze predict 2 only if antiping is on xd

**Comment by VxMiMxV** [comment]
After some more testing default should be set to 0, in some situations it's almost impossible to tell which way your tee is moving with it set to 2.
Example:
![Bleh](https://user-images.githubusercontent.com/47721445/57614119-d0232400-7578-11e9-8e7a-a6357bc2fd7f.gif)
(im holding left non stop)

**Comment by trml** [comment]
@VxMiMxV cl_predict_freeze could perhaps be more tunable, so that people can choose what kind of "ping" they want in freeze on any server. (cl_predict_freeze 2 currently simulates around 10-20 ping, and there could be more options like 50 or 100 ping).

I think having some prediction by default is useful, so that you don't get excessive lag on servers with >200 ping, but I'm not sure what the ideal value would be. Btw, what ping do you usually play with?

About the stoppers, I think that's how they actually work with strong and weak (can be compared with cl_predict 0).

**Comment by VxMiMxV** [comment]
I'm always at steady 68 ping.
And about the stoppers, the weak bobbing is useless so if its 'fixable' then it should be fixed imo.

**Comment by Learath2** [comment]
@trml is the tee actually moving or is this just prediction failing? If it's the former I'll just close this.

**Comment by trml** [comment]
@Learath2 The tees are actually moving, so it's not really possible to fix.

**Comment by Learath2** [comment]
Well if they are actually moving, there is nothing to "fix". If we "fixed" it it'd cause unexplained behaviour like tees held near a freeze tile getting frozen without actually touching the freeze on screen.

Nothing to fix
