### ISSUE TITLE
some "bugs" with speedups in editor

### ISSUE THREAD

**Issue by VxMiMxV** [ddnet/ddnet#1916]
1.Selecting and pasting speedups in the editor is weird.
![2new](https://user-images.githubusercontent.com/47721445/65196915-66b0a600-da81-11e9-8647-914ee9079aaa.gif)
SEEMS like speedups with 270 rotation and above bug out the selection tool, when these speedups are on the right wall of the selection sometimes they break all other speedups its really weird though.

Here:
![3new](https://user-images.githubusercontent.com/47721445/65196954-93fd5400-da81-11e9-9301-fcb7a54143c7.gif)
It's fine.

Here:
![4new](https://user-images.githubusercontent.com/47721445/65196966-a4adca00-da81-11e9-856b-af4d8d2fcef7.gif)
It breaks.

Here:
![1new](https://user-images.githubusercontent.com/47721445/65196969-ad9e9b80-da81-11e9-8b88-3bb040ef1c9d.gif)
It works.
I honestly don't know whats wrong with it.

2.Can't set arbitrary rotations past 315.
![2019-09-19_01-58-44](https://user-images.githubusercontent.com/47721445/65196819-0e79a400-da81-11e9-8833-1085ec9156e3.gif)
Always resets to 315.

**Comment by Learath2** [comment]
I think I narrowed this down to `CLayerTele::FillSelection`. Hopefully will figure it out in an hour or so.

**Comment by Learath2** [comment]
Okay my initial finding was wrong, but I did find where the bug is.

It's a branch in `editor.cpp:2599` which treats all layers derived from `CLayerTiles` as a generic tile layer, forgetting to copy over vital data, even after fixing this branch however;
A branch in `layer_tiles.cpp:1381` which ignores the brush's settings if they don't match the editors settings (which they don't).

I'm not sure what the second branch is trying to achieve, so idk how to fix this properly.
