### ISSUE TITLE
Bug with skin custom colors

### ISSUE THREAD

**Issue by Ekidoxx** [ddnet/ddnet#2055]
Take for example the [PsychoWolfe](https://ddnet.tw/skins/index.php?search=PsychoWolfe) skin, because it is truly white.

With _custom colors_ disabled, of course both the body and feets are white.
But if you enable _custom colors_, and drag `Lht.` sliders to the max... body becomes grey for some reason, while feets stay white as they should

| Custom colors _disabled_ | Custom colors _enabled_ |
|                  :---:                   |                :---:                   |
| Hex: #FFFFFF                     | Hex: #C0C0C0                 |
| HSL: 0° 0% 100%              | HSL: 0° 0% 75%               |
| RGB: 255 255 255             | RGB: 192 192 192            |

It works same also for dummy

<hr>

![Skin -- custom colors 1](https://user-images.githubusercontent.com/14035306/73609639-0786a480-45d0-11ea-89a5-0954902ca74d.png)
![Skin -- custom colors 2](https://user-images.githubusercontent.com/14035306/73609641-09506800-45d0-11ea-98f9-7ae2500a4aff.png)

**Comment by GiuCcc** [comment]
Actually some skins can have white feet, like: bluekitty, pink.
Most skins cannot, like: cammo, coala.

**Comment by archimede67** [comment]
This is due to how skins are loaded. Basically for every skin, two textures are actually created:
- a texture which is the image that you downloaded, which is used when having "custom colors" disabled
- a grayscale texture which is then recolored when having "custom colors" enabled

The game use a particular algorithm to compute the grayscale texture, which may not be the same algorithm that you can find in other image editing software. That being said, it will always be different from the original texture, even for white skins.
In your example, on the left is the normal texture and on the right is the grayscale texture, without any recolor (applying a white color will give you the original grayscale texture, nothing changes).

Therefore, this is not quite a bug. It has been like this forever and I don't think we ever want to change this as it would break everyone's skins.
