### ISSUE TITLE
Localize the editor

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2412]
Pipou suggested it.

I'm against it since it causes more work for translators and most players will never see the editor anyway. And once you're mapping, you probably have to submit your map somewhere and communicate in English anyway.

Other opinions?

**Comment by Patiga** [comment]
The button labels are (judging from my experience) cryptic and non-descriptive. Any small icons would do the job just as well.

I don't see a reason why the awesome help texts at the bottom shouldn't be added to the translation. They try to guide you through the editor and could actually be expanded upon.
Problematic is that its very easy to miss those, i forget them like every week and am glad every time i rediscover them.

Please keep the names of the game layers (Game, Front, etc.) in the saved maps in english though, since this is uniform ever since the last time the editor was localized.

**Comment by gerdoe-jr** [comment]
We can localize every elements' descriptions, no more. Because elements' names just unlocalizable(huh). Russian community, for example, is always using "tiles, envelopes, entities..." without any translation, there are no words for it.

**Comment by def-** [comment]
> They try to guide you through the editor and could actually be expanded upon.

It's a lot more work for the translators while most players will never use the editor.

**Comment by Patiga** [comment]
Well the editor features have to be explained somewhere. If not through the client then in some external source. In that case a link to that source would probably help, however such an external source will probably never be translated at all.

**Comment by Nyte-BK201** [comment]
I would support the idea of localizing the specified descriptions which in the bottom editor. This, of course, works to ease the understanding of obscure buttons. Won't cause too much effort and worth it.

**Comment by KuleszGG** [comment]
I think that translating the functions would be very useful, not everyone can speak English and some would like to build maps.

**Comment by C0D3D3V** [comment]
I have also come across the explanations for the editor in the code and wondered why they are not translated. I see no reason not to. It's only a one-time extra effort for translators and they can take their time because as far as I know English is displayed by default if no translation is available.
