### ISSUE TITLE
revert #2424?

### ISSUE THREAD

**Issue by skist** [ddnet/ddnet#2529]
Saving weak and strong on the tees seems kinda unfair for me because players could swap it in the past. Sometimes you come to a part that will be really hard if you got weak, for example rocketfly or dragging down a deepfreezed tee.
Solutions can be adding /spec by default or going back to the old behaviour of saving with weak and strong.

**Comment by heinrich5991** [comment]
Adding /spec by default is probably not a solution, at least it would have the same problems you specify.

I see that we had something that allowed changing weak/strong and it's not there anymore, which is a change of gameplay in a sense.

I'd argue that the old behavior was quite non-discoverable and annoying to use.

Non-discoverable: As a new player, there's nothing about save/load that screams: This changes gameplay in some sense. Rather, it'd be expected that save/load replicates the game state perfectly. (Hmm, could we perhaps add another load command that allows to load in some other strong/weak order?)

Annoying to use: It requires the players to save, **wait a minute** and load again. That's a bit too annoying for a standard gameplay feature IMO. I wouldn't really like getting rid of the minute either though, otherwise it could lead to common usage and thus race times no longer representing actual play time, but rather play time + number of weak/strong changes in minutes.

What do you think about these two points?

(Simply reverting #2424 is unwise, it also fixed other things.)

**Comment by Learath2** [comment]
We can always revert f2b5abb1

**Comment by heinrich5991** [comment]
I'd prefer to add a new command that changes the weak/strong order instead if we do add it back.

**Comment by Ekidoxx** [comment]
Honestly, why allowing `/spec` by default is bad idea? Especially with now visible players in spec?

**Comment by heinrich5991** [comment]
You can kinda cheat by disappearing out of the map. It'd be better to have a key for getting strong without disappearing.

**Comment by Zwelf** [comment]
I plan on writing a fix for this and the new `/save` behavior after completing #2465 (the last thing missing there is compiling with msvc).
