### ISSUE TITLE
ID in record_teamrace is broken

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2561]
@Zwelf Another one for you I guess:

ID in record_teamrace contains weird characters when a team save is inserted for the first time: `«[7SLÊ\nk+` vs previously: `912b616a-d1ae-11`. Probably the ID shouldn't be a blob?

**Comment by Zwelf** [comment]
The TeamID is indeed the only place where we use VARBINARY(16) instead of VARCHAR(36) to store uuids. You can use `UUID_TO_BIN` and `BIN_TO_UUID` functions in MySQL[[1]](https://stackoverflow.com/a/45186851). I convert the UUID to binary now to avoid cutting them off (forgot to mention it as a behavior change in the PR).

**Comment by def-** [comment]
This makes copying it quite annoying, but cutting it off is even worse. Can we seemlessly switch to VARCHAR(36)?
