### ISSUE TITLE
Duplicate entries when sql server has bad connectivity

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2636]
@Zwelf I guess this is a result of us having multiple master write servers, right? I have to daily fix our replication by skipping inserts that happened on 2 sql servers. Should we just reduce it to 1 sql server for writing?

**Comment by def-** [comment]
I think this also leads to better team ranks being overwritten by worse ones. Chao experienced this on NUT_short_race7 3 days ago. I can see that the worse team rank overwrote the better one. I feel liek we never had these kinds of issues before the big SQL changes.

**Comment by Zwelf** [comment]
> skipping inserts that happened on 2 sql servers

I don't know yet, why ranks would be written to two MySQL servers. ddnet only tries a second insert, if an error occurs during the first insert.

> Chao experienced this on NUT_short_race7 3 days ago

I think this was caused by the inconsistency from 3 days ago #2618? On GER2 both databases (db1 and db2) were read from and written to, but ranks only propagated from db1 to db2.
If the rank was updated in both databases, the conflict could be resolved either way (better/worse team rank).

I got a saved duplicated due to the inconsistency (3 days ago). Probably:
1. loaded `a` save from db2
2. saved `b` on db2
3. loaded `a` from db1 (2 hours later than 1.) <- duplicated

save `b` is still loadable

The duplication might have something to do with the replication setup. But I'm not sure, since you didn't have these problems before:
* https://serverfault.com/questions/336888/
* https://lists.mysql.com/replication/1748
* https://forums.mysql.com/read.php?26,91444,91444

As far as I can tell the only bigger thing I changed to the MySQL connections is, that now only one thread is working on all request and not anymore one thread per request.

**Comment by def-** [comment]
Yesterday I was doing a large update on one of the DDNet SQL Servers, which caused all other inserts to wait. Then I noticed that the same inserts that were waiting on the main server also got inserted on the second SQL server. Then an hour later the first SQL Server was done with its update and also ran the inserts that were queue for an hour. I guess that's how we end up with duplicate entries.
