### ISSUE TITLE
Entities are hidden in case if we didnt received server type

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#2750]
we do "mask" entities by default. We dont do it in order if we know that the server is not a DDNet.

But if we do call CMapLayers::OnMapLoad() before getting NETOBJTYPE_GAMEINFOEX then entities map will be prepared to be used with ddnet entities (entities will be "masked")

> abcqwertyToday at 02:54
> why does entities not work on noby fng in the new version
> the only spike that shows up are the red spikes

P.s.: I dont understand the  initial solution to hide problem on client instead of fix problem on server

**Comment by BannZay** [comment]
what would happen when new entity will be here so previously masked entity become unmasked. Sounds like we just delayed the problem... and introduced more (this issue)

**Comment by Jupeyy** [comment]
that's indeed a problem, even if we reset the mask always, we get unused tiles for ddnet again,
@heinrich5991 is there any chance that the ddnet game info is sent before loading the map?

**Comment by BannZay** [comment]
If its possible I would remove this "feature" at all it kinda does opposite thing to what the overlay entities were originally created (to test maps).

If no, we should add clientside setting to prevent masking I dont want to not see problems on maps when I testing them.

**Comment by Jupeyy** [comment]
Someone with network knowledge wants to fix this?
I can try too, but i have no overview what mods/ddnet versions will break with my patches(i'd remove the current GAMEINFOFLAG_DONT_MASK_ENTITIES and send a mod info packet before the map info is sent)
or alternativly enable unused tiles again.

the problem was introduced in f31e081bd426a747a24783fd2df0ef9c712fc14d

before that commit the gametype was checked by the servers mod string

it currently affects all players with the new renderer.

@def- @Learath2 @heinrich5991

**Comment by Jupeyy** [comment]
Should've been closed by the pr already
