### ISSUE TITLE
Establish a minimal testing process before a release.

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#2857]
It should have a generic checklist and then a specific checklist for the changes made in that version.

I also suggest being more patient with releases, make sure everything is okay and not rush stuff.

I know we have problems mostly because people don't even try the nightly builds, but maybe we can make it easier by telling people what to look for.

Personally I will try to test upcoming clients, but I can only test on Linux amd64 and Windows 10 (with modern graphics).

I'm not really experienced with game testing but here is a general idea for the generic checklist:

- [ ] Client and server don't crash when opened.
- [ ] Client doesn't have apparent visual bugs.
- [ ] Client tabs work as expected.
- [ ] Client sound works.
- [ ] Client autoupdater works.
- [ ] Client with a 4:3 resolution doesn't look bad.
- [ ] Server can connect to a sql server.
- [ ] Server physics are not broken.
- [ ] Server /save feature works (specially if new info is added)
- [ ] Server /team command and related works.

> Server physics are not broken.
Maybe there is better wording for this one, I am referring to the issue that some updates broke the collision completely and stuff like that, then we had to remove ranks iirc.

We can also have a very basic map with most of the features you can have in a map for quick testing.

If you know a better method suggestions are welcome.

**Comment by def-** [comment]
This would not have caught most of the recent failures, since they were in more obscure features (key binds in demo viewer with popup open, crash when using skin prefix in combination with skin downloader, server keeps running after client exit, "run server" didn't work when run from another directory, localizations missing in menus, websockets crashes in LAN tab). I think instead you should look at the actual features that were changed and test them in-depth. I try to do that before accepting a change, but it's of course never in-depth enough, and more eyes to review and test changes would help.

For autoupdater testing we'd need to add an option to switch to another autoupdater server and I'd have to prepare everything there.

1280x1024 Resolution should be checked, since it's 5:4 and even worse than 4:3.

**Comment by BannZay** [comment]
Introduce release candidate instead of nightly builds please.
I don't really care about small bugs in actively changing version

**Comment by BannZay** [comment]
I suggest to have branch with release candidate state. We got to merge fixes incoming into release candidate but I believe it will secure releases good enough

**Comment by def-** [comment]
Please no release candidate branch. I hate cherry-picking and resolving conflicts

**Comment by def-** [comment]
Instead we should aim to only merge PRs once they are ready for release.

**Comment by BannZay** [comment]
Otherwise people has not enough time to test "ready for release" version. 
I am not interesting in "deep" testing intermediate versions. Others might think the same.

If release candidate has no problems (or none reporting) = no cherry picking. So its more decision between cherry picking vs fixing problem afterwards, ie after release

**Comment by def-** [comment]
Ok, so let's try the release candidate thing for new feature releases. I think the RC time should depend on how big-impact the new features are. Let's test it with the next release. If bug fixes are required and other feature changes went in meanwhile, I will make an RC branch on demand.
