### ISSUE TITLE
Local server ranks not working

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2862]
As reported by Pipou on Discord

Probably a sqlite problem.

**Comment by def-** [comment]
![screenshot-20200918@164501](https://user-images.githubusercontent.com/2335377/93625504-5b6cbf00-f9e2-11ea-8ac7-b97eaca5ab1f.png)

**Comment by Zwelf** [comment]
Probably wrong screenshot? I tried the version from master and ranks still get written and commands like `/times` and `/rank` are still working for me.
Might be caused by setting `sv_use_sql 1` instead of the default `sv_use_sql 0`. Ranks/teamranks/saves would still get written to the fallback write server (`ddnet-server.sqlite`), but read operation would just fail.
If it is about importing old ranks, this would help: https://github.com/ddnet/ddnet/blob/master/scripts/import_file_score.py

**Comment by def-** [comment]
Oops, fixed the screenshot

**Comment by Zwelf** [comment]
Okay, not caused by `sv_use_sql 1`, since `/top5` returns something. Does Pipou has the server logs? Might still be related to #2737.

**Comment by Zwelf** [comment]
Checked again, but I can't reproduce this. Needs more information to be actionable.
