### ISSUE TITLE
Save autorecorder demos with better file name

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#297]
instead of autorecord_date.demo it should be mapname_date.demo

**Comment by east** [comment]
Maybe use "date_mapname.demo" instead so the demo files still will be sorted chronically when using simple alphabetical order.

**Comment by def-** [comment]
yeah, even simpler and good enough probably.

**Comment by nzyuzin** [comment]
In my use case I'm usually interested in a specific time at which some ctf2 game was played.

For mapname_date naming I would look first for ctf2 (which is cool, since I'm mostly interested in ctf2 demos) and then check specific day with specific time.

But for date_mapname I would still have to look for 2015-08-22 and then look for 1 am to only then get to ctf2. That's just the same as I do currently.

So I can't see what date_mapname naming changes, but mapname_date looks really good to me.
