### ISSUE TITLE
Area over skin selector sometimes also selects skins

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2990]
gerdoe reported on Discord, has a video. I also got it once.

**Comment by Learath2** [comment]
To reproduce, you need to get a bit of the skin button rendering. Then it should work consistently. It's because clipping in teeworlds is only graphical until 0.7.sth

https://github.com/teeworlds/teeworlds/commit/a809e59e6a884a3713e46472d19b189491923875
https://github.com/teeworlds/teeworlds/commit/435fb05de161c7851b5ad466ebea290fe809d6ad

0.7 fixed this with ^^ We can port something similar over

**Comment by def-** [comment]
So this isn't really a new bug? No need for 15.1 then I guess.
