### ISSUE TITLE
Pair up players automatically?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3172]
I noticed players often play with dummy because they can't find a partner quickly. Should we provide a way to pair up players automatically? I'm honestly not sure it's a good idea, but just wanted to throw it out there.

Maybe automatically select servers where you have low ping, select difficulty (Novice 3-5 stars) and check if it should be a map you haven't finished yet. Then you'd automatically get paired up with another player looking for a partner, fitting your profile, on a server fitting both of your interests.

**Comment by b3z** [comment]
I think it'd ne great for newbies to have some button in the server browser which offers "find me a teammate" or something. I think especially for people who are new to TW it is hard to find out on which server to play and how to find teammates.

Another downside is that we will have to track way more of a player like skill level etc. if a good pairing should be garanteed?

**Comment by def-** [comment]
We can't track player skill level since we have no accounts. It would only be done based on the choice of difficulty.

**Comment by b3z** [comment]
Of course you can calculate a skill level by looking at the maps they finished. People who finished:

* JustFly - Hammerfly
* The Kobra maps - general understanding of ddrace mechanics
* Aim maps - edge hooks etc.

and so on

Also we know which mechanics are involved in which map.

E.g.
![image](https://user-images.githubusercontent.com/47346598/96978805-0ced9b80-151f-11eb-82bf-8c9a3d40612b.png)

**Comment by def-** [comment]
No, people can just use any name. There are some names used by mulitple players regularly with totally different skill levels. See Brazilian jao for example.

**Comment by b3z** [comment]
> No, people can just use any name. There are some names used by mulitple players regularly with totally different skill levels. See Brazilian jao for example.

Fair enough.

**Comment by murpii** [comment]
errr, I wrote this yesterday night. not sure why it didnt send it:

Interesting, A matchmaking system. This would be definitely a huge step forward.

I only see a few problems though which needs to be thought through:

- You'd have to force people to stay in a team unable to just join t0 afterwards or preferably have them join an empty server, else this would be kind of pointless. 
- I also fear people would just abuse the system [as an example]: queue and then just leave, queue again, leave and so on. Such system would require measurements to penalize players which abuse the matchmaking queue, but this however probably requires a proper account system.
- As of now, players which are complete new to the game require a proper tutorial. If they use the matchmaking system, then end up with another complete new player, they would end up frustrated, unable to get anything done because they have no clue how the game works or what the goal is.

A good algorithm to get a working matchmaking is probably pretty difficult. E.g it probably would require a behavior score, which then requires a report function for said abuse mentioned above. To get everything running properly, would take a pretty long time I imagine. So long in fact people would get frustrated, go back and stick to the server browser :(

One thing I can imagine could work right off the bat is a system which pairs up 2 or 4 players which are already on a server, standing around at the start line using /queue or something.

**Comment by def-** [comment]
> You'd have to force people to stay in a team unable to just join t0 afterwards or preferably have them join an empty server, else this would be kind of pointless.

Nope, I'd put them on same server in team 0 and tell them "X is your partner, go ahead"

> I also fear people would just abuse the system [as an example]: queue and then just leave, queue again, leave and so on. Such system would require measurements to penalize players which abuse the matchmaking queue, but this however probably requires a proper account system.

Knowing our community, true.
