### ISSUE TITLE
Feature Request: /timesnear

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#3199]
Cousins with the /teamrank command, except allowing you to figure out who you [probably] finished a map with on team 0.

Ex usage: /timesnear d3fault
*** 5 years and 9 months ago, 4:20.69     <-- same info as /times d3fault
Skeith +0.01 (4:20.70)
Broken -5 (4:15.69)
[etc, giving 5 nearest finishes]

The plus and minus indicate whether they finished before you or after you, but the list is sorted via distance from your time... because the tees that finished nearest your time are most likely the ones you were actually playing with.

That above output assumes only one map finish, but it should iterate your multiple map finishes and  show the finishes near you for each one.

Server "country" of each nearest player must match yours, that will make the results more accurate.

**Comment by def-** [comment]
I'm against it

**Comment by Banana090** [comment]
I'm against this particular approach too, but if the players wants some feature, why not add it? Just tell us why do you want this. Is that for searching for your t0 teammates? Wouldn't it be better to implement a website feature which allows you to see every day finishes on map, so you can look for "nearest" yourself? Because your approach does not guarantee that those people are your teammates at all.
