### ISSUE TITLE
~~Quick~~ guide on how to implement accounts

### ISSUE THREAD

**Issue by Banana090** [ddnet/ddnet#3244]
Everyone wants accounts, but nobody knows how to implement them correctly so nobody loses their ranks and does not get annoyed by registering. I know how, here is a guide for you:

Read it until the end please, there are a lot of things I should mention but my English is pretty bad, so I did not manage to formulate it in the right order.

Let's first mention three types of "account":
1. **Steam**. Account, that uses SteamAPI for authentication, can only be used when running game through steam of course.  Profile data is attached to SteamID
2. **DDNet account**. Register on DDNet website and use Login + Password for authentication.  Profile data is attached to Login
3. **No account / Simple Name**. The default behavior we currently have. Do not send any authentication requests and behave like it used to. Profile data is attached to name currently used by client

Steps to create awesome account system:
1. Database containing player's info (points, finishes, times...) should also have field to determine whether "Name" field is: Simple name, Login or SteamID.
2. There should be new database for Login, Password, E-mail and maybe other extra info for DDNet-registered accounts you may need.
3. In client's settings there should be a new menu for "Profile" where you have options for Login through steam, Login via DDNet account or "Do not use authentication"
4. When "first time" (read as: There is still no settings for auth) running client through steam it automatically registers you using SteamID with help of SteamAPI. I did not work with this a lot, but I know there are easy functions to get real unique user ID that can not be faked. For every other launch it will authenticate you automatically via SteamID if you did not disable authentication in "Profile" settings or switch it to use DDNet account instead.
5. When "first time" (read as: There is still no settings for auth) running non-steam client there should be a popup that offers you to login with DDNet account or register it. There should also be button for "Do not use account" that sets default behaviour to "No account" variant.
6. When joining DDnet server if authentication setting is not set to "No account" client sends an extra package to login on the server. If it was not received or client received error: show popup about that. If authentication was OK, server now stores data for this client of his auth info and type. If client uses no account - just don't send anything and server by default determines it as "No account" user and behaves like it used to now. 

Every new created account have no points or finishes on it, but when logged in your finishes should be saved for your current account ignoring the name you are using in client. 
So after all of this done players still can play as they used to or create a new clean account and play using it.

To move your points, ranks, finishes and all other profile info into newly created account old players should ask admins to move it and prove that this name belongs to them. If admins are convinced that name belongs to this person they move all profile data into account and delete data for name-only, so it's clear and safe now.

So the idea here is not to force everyone use accounts, but rather offer it to players, so **they decide if they want to use it or not**. As well as **support old system without any changes to it**.

Now we should add some cool features for account-registered users that "no account" users can not have to motivate players create an account to play with. For example it could be hats for skins that can only be used when you reach certain amount of points, it could be achievements or something else.

Pros of implementing all things listed:
1. Achievements
2. No fakes
3. "Points shop" with things you can use if you reached certain amount of points like special hats on your tee, colored nickname or whatever
4. Unlimited self-nickname changes any time you like
5. Dummy automatically finishes for your account, no need to worry about accidental finish on dummy name
6. No need to save any IPs or something
7. ... (All other cool things are related to "No fakes")

Cons of implementing this:
1. There will be a lot of players asking for move their points and finishes into their new account. Much work for admins
2. Implementing all of this is kinda hard and will take some time

There are some others things that should be implemented to make use of it easy for users and stable, but I will wait until you say "wow, that's cool, let's do exactly what he said" and then I will add more details. Or you may try to convince me that system wont work.

**Comment by b3z** [comment]
Problems I see:
* dealing with peoples personal data
* handling security guarantee 
* "Points shop" diversifies skilled people from new people and builds bigger social distance between them (right now per se all players on a server are the same which doesn't lead to prejudices). I think it would make it harder to get into the game for new people. Right now the beauty is that a good player comes together with a not so skilled player and just plays with him. Would he if he knew that the guy is a noob? How is tw tought then? Also pay2win thought.

* "Unlimited Nickname changes" - sticking to one nick is a good think in my eyes since it is the only way to recognize players. Also one nick leads to more responsibility. And less rude behavior.

* "Achievements" - you see you need to ask yourself why tw is so addictive. It is because the gameplay is a lot of fun and because you kind of follow a social schema in most mods where teamwork and helping each other is necessary to succeed. Don't destroy that by just chasing achievements while the biggest achievement should be to finish a map together. Also in tw success doesn't really matter right now. This is why it is a nice escape from real live (sounds dumb but is true). Preset achievements would probably ruin that because success would be measurable and present all the time?

These are my thoughts. Maybe some are too paranoid but I think they should be heard.  

I would rather go with an account system like kog uses.

**Comment by Banana090** [comment]
Forget it. You know nothing about game development and will never improve this game. 
This community can just complain, not do something

**Comment by b3z** [comment]
Its just some criticism...
