### ISSUE TITLE
Show other peoples key presses while they are frozen

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#3281]
I've asked on discord but didn't really get an answer. Is this possible to implement?

**Comment by def-** [comment]
Probably requires larger changes. We don't send the keypresses from server to client if player is frozen.

**Comment by trml** [comment]
Was thinking about this too (as well as sending the true weapon in freeze). But for the network part this would either require an additional flag in ddnetchar, or a new netobject. Is it possible to add another flag to DDNetCharacter for this?

With a new netobject it would also be possible to send additional things, for example whether someone presses fire or not. Would that be of interest? Otherwise I think adding an extra flag would be the easiest.
