### ISSUE TITLE
sql message from thread overlapping

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#3320]
![image](https://user-images.githubusercontent.com/35420825/99287362-6e610b80-283a-11eb-8a2e-2de96616ad08.png)

**Comment by fokkonaut** [comment]
![Uploading image.png…]()

**Comment by fokkonaut** [comment]
![image](https://user-images.githubusercontent.com/35420825/99287418-846ecc00-283a-11eb-83f1-9f6fe84117f9.png)

**Comment by def-** [comment]
@Zwelf Good ideas?

**Comment by Zwelf** [comment]
`dbg_msg`s should be thread safe on linux. Maybe they aren't on windows? The second image looks broken. In my opinion the first image is ok. If the first image should be fixed, I would reduce the output of the rcon password to one line.

**Comment by fokkonaut** [comment]
It was meant to have be like that to instantly spot the password on startup. Would not change.

**Comment by Learath2** [comment]
Well due to the nature of asynchronous io, we can't have "block"s of text output. The way we have aio implemented is agnostic to "messages". It just outputs a buffer so something like this either requires a way to "lock" aio, flush the buffer, output the block, flush the buffer, "unlock" aio OR a queue of dbg_msgs instead of just a large buffer of characters.

**Comment by Robyt3** [comment]
Seems like too much effort for a minor inconvenience. The loggers are thread safe, so individual lines should never overlap.
