### ISSUE TITLE
rcon tele

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#3324]
tele available only  on id
what about name
simple 
tele triki bro
or
tele bro triki

status dynamic but i wanna bind for static

**Comment by Learath2** [comment]
I wanted to do this but there are issues with it:
- First is that it requires a rather large rework of the console to make is name aware (harder than one might expect since the console is shared between the client and the server).

- Second, said rework has ambiguity issues rising from people having numerical names.

Example: What would `kill_pl 50` imply? Does it mean ban the player named 50 or the player with id 50?

This could be alleviated with requiring quotes for numerical names but that's not intuitive, or maybe named arguments like `kill_pl name=50` vs `kill_pl id=50`. Either way makes the rework for the console even larger.

**Comment by heinrich5991** [comment]
CC #1489

**Comment by trikiman** [comment]
kill 50 it is nubmer 
kill "50" name

**Comment by Learath2** [comment]
I already made that proposal too. It still requires a rather large rework
of the console code

**Comment by def-** [comment]
I'm very much against that. Trolls will use numbers as their names to trigger mods not knowing that. It should be explicit, at least when the value can be interpreted as both.

**Comment by Learath2** [comment]
Oh there is that too, I always forget the human factor in these matters

**Comment by trikiman** [comment]
> Trolls will use numbers as their names to trigger mods
don't really understand what "mod" u talking

**Comment by trikiman** [comment]
U just dont know about other cmd. but i dont know how they can troll with rcon tele.
maybe just not allow [name] for all cmds.

**Comment by def-** [comment]
We should implement it as a generic solution for all commands that take a player id, which includes kick and ban.

**Comment by trikiman** [comment]
> We should implement it as a generic solution for all commands that take a player id, which includes kick and ban.

i still no understand how ppl will troll

**Comment by trikiman** [comment]
Ah mod it is moderate. ye i got that. Though mod = modification

**Comment by kamillentee** [comment]
I think this one should be closed. cl_show_ids show the ids in the scoreboard. Its faster to write and not ambiguous.

**Comment by trikiman** [comment]
> I think this one should be closed. cl_show_ids show the ids in the scoreboard. Its faster to write and not ambiguous.

it's about bind, u can always use one bind and never edit.
