### ISSUE TITLE
Antiping: double jump particles of other players invisible

### ISSUE THREAD

**Issue by Patiga** [ddnet/ddnet#3361]
While antiping is turned on, you don't see the double jump particles of them.
This is a problem imo because
1. it could/should be confusing for new players
2. seeing where exactly the other tee double jumped can make tricks much easier to understand

**Comment by def-** [comment]
@trml I guess you can't show the particles since the event will always be in the past when using antiping?

**Comment by Patiga** [comment]
Hm how is it different to for example hammer hit particles?

**Comment by trml** [comment]
Yes, you would see the jump in one place and the player already at another place. I tried it once, and with 200+ ping and many players on the screen it made things look more confusing, so at least I think it shouldn't be standard.

Hammer is slightly different, since it happens less frequently and often gives you "more important" information. And the hammering animation itself is also delayed.

**Comment by Patiga** [comment]
I can imagine that with 200+ ping many particles and tees will look out of place.
If you have 200+ ping you should be switching servers and the situation that you can't do that should be rather uncommon (meaning that imo it should be on by default).
Antiping is used by regular players with regular pings and for me, the exact position of double jumps can be quite important.

**Comment by WatermelonDriveway** [comment]
I'll add this here since it wasn't mentioned yet - The DJ audio file doesn't play either for other tees while antiping is on

**Comment by heinrich5991** [comment]
I also find this confusing. At least the sound would be nice.
