### ISSUE TITLE
[question] sharing dotdir with teeworlds

### ISSUE THREAD

**Issue by AMDmi3** [ddnet/ddnet#3385]
Hi, I'm currently working on official DDNet package for FreeBSD, and I've noticed that it uses the same dotdir as teeworlds (package of which I also maintain). The question is whether such configuration is safe, e.g. can ddnet modify (and possibly break) teeworlds configs or can teeworlds modify (and possibly break) ddnet configs, taking into account that either teeworlds or ddnet configs format may change in the future. Wouldn't it be safer to use dedicated dotdir for ddnet?

**Comment by def-** [comment]
Hi @AMDmi3! Great to hear about a FreeBSD package!

Yes, probably we should take the plunge at some point and move to our own config directory. Unfortunately this will probably not be a good experience for the existing players though.

There should be no problem at the moment though, since we use `~/.teeworlds/settings_ddnet.cfg` while Teeworlds 0.7 uses `~/.teeworlds/settings07.cfg`.

This is a duplicate of https://github.com/ddnet/ddnet/issues/2698

**Comment by AMDmi3** [comment]
Got it. If the switch to dedicated dotdir was decided I could use it right away for the port, but as I understand it's not really the case, so I guess I'd stick with upstream as long as it doesn't conflict with teeworlds. Thanks!

**Comment by AMDmi3** [comment]
Btw, I've just committed FreeBSD port: https://www.freshports.org/games/DDNet
