### ISSUE TITLE
Extending game.png

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3442]

**Comment by heinrich5991** [comment]
I'm in favor of making the current game.png larger, and if encountering an old-style game.png, we use the new default icons.

Detecting the new-style game.png is done via aspect ratio.

The default game.png will live in game_ddnet.png to achieve compatibility with other clients.

**Comment by heinrich5991** [comment]
This would allow people to share the game.png in one file.

Downside mentioned by Jupstar: You need an image editor to match an old-style game.png with a non-default set of new icons.

**Comment by Jupeyy** [comment]
My argument in 1 sentence:
Modularity is nicer, bcs it allows you to use the default game.png while matching the new icons more with your entites(which will probably look similar) and also doesn't break any compability, independent of stripping/truncating

A new asset tab is not harder than mixing two variants of game pngs

**Comment by Learath2** [comment]
Hm, I think I like a separate game_ddnet.png with just our icons better. Merging both makes mixing and matching harder for users.

There are many game.pngs out there that people already use. If they don't like our default icons they are forced to create a new merged game_ddnet.png

**Comment by l-ouis** [comment]
I think putting the icons in the already-existing file is a little complex, but also don't create a whole new assets tab for a handful of icons (it's like the main menu cursor, it probably won't be customized much)

I think there's a better way to solve the complexity of sharing someone's custom textures instead of just fixing it in one instance (i.e. we should allow people to share all of their game.png, particles.png, etc. with one easy method instead of just allowing them to share game.png + icons easily)

for example, maybe we could implement some sort of system where someone can just have a folder containing whatever images they want (game, particles) and put it in some assets folder which would automatically put each image in their corresponding assets tab.

**Comment by heinrich5991** [comment]
Will be solved by #6753.
