### ISSUE TITLE
after 14 hours some bullets stopped moving and my grenades don't rotate

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3533]
As reported by Im 'corneum: Well maybe you can recreate it. I used cheat engine to speed hack and after 14 hours some bullets stopped moving and my grenades don't rotate. Even after reload

Maybe we can try out https://github.com/wolfcw/libfaketime or something similar to see if we can reproduce these physics problems

**Comment by Chairn** [comment]
Do you have a demo map or the map name you used to get this bug?

**Comment by C0D3D3V** [comment]
Since he used a speed hack to manipulate the client (or server (unclear)), I don't think it's a high-prio bug. 
Proably the client desynced so far that the action ticks did no longer create the animations.

**Comment by Chairn** [comment]
I put highprio in case its the latter case where freezing bullets wont work anymore which can allow cheats

**Comment by C0D3D3V** [comment]
if he is in control of the server he can allow cheats just like he wants xD It then also does not matter if he use a speed hack on the server.  But yes would be interesting to debug such a situation, maybe we can improve syncronisation and hardening against external speed hacks.

**Comment by Chairn** [comment]
Or you can stay on the server just like Konsti does and wait for the bug to trigger. 14 hours is not that long, but i guess it's 14 hours with the speed hack, so probably several days in real time?

**Comment by def-** [comment]
We have game servers with 30 day uptimes occasionally, so this can definitely happen in real cases too.

**Comment by Chairn** [comment]
I thought they auto restarted when empty during night ?

**Comment by C0D3D3V** [comment]
I have tested the scenario and captured a small part (because my PC was lagging already because of the VM) of my testing in this video: https://youtu.be/55YK5fwRibw
Result:
Our client is pretty robust against speed hack. It desyncs fast, but as soon as you turn the speed hack off it syncs fast again (because the client tick is stopped evolving after to much difference with the server gametick). Prediction is mainly the thing that suffers from the desync a lot... teleporters are not predicted so tees just floating through them.

The server works well with speedhack, you can run a client that has speed hack on the same multiplayer as the server pretty stable. Even multiplier of 500 works without disconnect :D sound effects getting already annoying with multiplayer of 20

I could not reproduce the described behaviour, all bullets and grenades worked and where correct animated even after 14h

**Comment by def-** [comment]
Thanks a lot for the work @C0D3D3V
