### ISSUE TITLE
Local versions for /rank and /top5

### ISSUE THREAD

**Issue by kyle-bradley** [ddnet/ddnet#3655]
Larger communities can dominate the scoreboards and drown out the progression of smaller communities. It would be more useful if people can relate to the people in the ranks.

Local /rank to filter results based on country groupings e.g. https://ddnet.tw/stats/

**Comment by def-** [comment]
True, my main worry here would be that we already have so many commands and making them more complex makes it even worse.

**Comment by houseme-kyle** [comment]
Fair enough, I'll try to think of a way to potentially address that.

**Comment by houseme-kyle** [comment]
I think we could apply some general UX principles here, where we prioritize the "novice" user experience but accommodate for advanced users.

The average user wouldn't be able to relate or be interested in their position relative to global players as the names are unfamiliar and are often on another tier of skill. It could also discourage engagement as it would take a significant time before these commands are meaningful to them.

My suggestion would therefore be to make the basic rank/top commands default to their region. You could then take in a flag if you want to see your position on a global level. By the time your global position would be relevant, you would be an advanced user and know about it or even have a bind.  

My hope is that it would foster growth within the smaller communities as they get "rewarded" sooner.

**Comment by houseme-kyle** [comment]
As a separate point, but somewhat related, are we able to retrieve usage stats for each command? Could be helpful to deprecate a few if they aren't being used.

**Comment by def-** [comment]
But most players are on GER server and most top ranks are on GER server too. This won't help them at all. We also sometimes randomly add new regions (like Turkey), so there will be nearly no top ranks there.

I think showing the global times is already ok, and showing your percentile rank as we do makes it better to gauge your rank compared to the rest of the world.

**Comment by houseme-kyle** [comment]
> But most players are on GER server and most top ranks are on GER server too. This won't help them at all. We also sometimes randomly add new regions (like Turkey), so there will be nearly no top ranks there.
> 
> I think showing the global times is already ok, and showing your percentile rank as we do makes it better to gauge your rank compared to the rest of the world.
> 
> > My hope is that it would foster growth within the smaller communities as they get "rewarded" sooner.
> 
> Hm, this is not a bad point. Other opinions?

Don't get me wrong, I am not saying that it should be removed. I am saying the /top5 should be local, whereas the global is either /top5 global or /globaltop5. For the bigger communities like Germany, it wouldn't make a difference as they are pretty much are the global list :)

Regarding your point about Turkey, I think that is an excellent example of what I am trying to solve. As a fresh community, they can get that excitement of being the first to finish a map amongst their peers or get a top score. 

There may be other ways to go about it. Open to ideas :)

**Comment by houseme-kyle** [comment]
I wasn't too happy with my solution provided. Didn't want to disadvantage anyone through this, which is the point you raised. It also doesn't solve your other concern of having a duplicate for every rank/point command. I think I found a good compromise that addresses this.... why not have both :)

In the same command, you can show both stats. It could look something like this:
**/rank**
*** Zodiac's time: 01:37.16, requested by Zodiac
*** 250 global | | 3 local

or 
*** 250 global | | 3 local. Zodiac Time: 01:37.16, requested by Zodiac

or
*** 250 (3 local). Zodiac Time: 01:37.16, requested by Zodiac

Same options apply for
**/points** 
e.g.
*** Zodiac's points: 434, requested by Zodiac
*** 4560 global | | 12 local

**/top5**
*** ---------- Top Global 5 ----------
***  1. Zodiac Time: 01:40.23
***  2. Caidoz Time: 01:50.12
***  3. def- Time: 02:40.12
***  4. Starkiller Time: 12:40.14
***  5 Cor Time: 12:41.54
***  --------------------------------

~~5-second delay 

*** ---------- Top Local 5 ----------
***  1. Zodiac Time: 01:40.23
***  2. Caidoz Time: 01:50.12
***  3. def- Time: 02:40.12
***  4. Starkiller Time: 12:40.14
***  5 Cor Time: 12:41.54
***  --------------------------------

or
**/top3**
*** ---------- Top Global 3 ----------
***  1. Zodiac Time: 01:40.23
***  2. Caidoz Time: 01:50.12
***  3. def- Time: 02:40.12
***  --------- Top Local 3 --------
***  1. Zodiac Time: 01:40.23
***  2. Caidoz Time: 01:50.12
***  3. def- Time: 02:40.12
***  ------------------------------

Admittedly, the top commands don't work as well due to space issues. Thoughts on the above? Other options?

**Comment by gerdoe-jr** [comment]
Also can be closed?
