### ISSUE TITLE
External noobfilters

### ISSUE THREAD

**Issue by kamillentee** [ddnet/ddnet#3679]
The idea is to connect players to another server that exclusively hosts a noobfilter. Once a player finished it they will be autoconnected to the real map.

- you don't have to deal with players that !absolutely! don't fit to the current difficulty level
  - I am fine with players who have a somehow lower level than the map requires so the noobfilter should be slightly easier than the map. 
- slots are not blocked by people who try the noobfilter or people who are afk even after map change
  - you could even have multiple filter servers for one real server if too many want to join 
- older maps that lack a noobfilter (because the majority of ddnet players were pro enough anyway so the mappers got rid of filters) can be fixed. For maps like stronghold I still would only add a very very basic noobfilter, as the map usually gets played right after people finish multieasymap for their first time (and they have fun)
- new maps dont need their own filters
- when you kill or connect you dummy you don't need to play the filter again
- there should be an option to connect as spectator only but joining the players should not be permitted without completing the filter first
- fixes #3486

**Comment by def-** [comment]
I don't like it. This makes it harder to communicate with the new players, doesn't allow them to watch pros (without the extra step to figure out how to join as spectator only; more complexity). A warning seems better than putting them into a prison they have to escape from.

**Comment by edg-l** [comment]
I don't like this either.

**Comment by Learath2** [comment]
-1 from me too

I would however like to have accounts track some metric so we can warn players on maps that seem too difficult for them

**Comment by kamillentee** [comment]
> I don't like it. This makes it harder to communicate with the new players, 

Ok I see that, (even if I often have the feeling they can't see or use the chat anyways)

> doesn't allow them to watch pros (without the extra step to figure out how to join as spectator only; more complexity).

This could be easily fixed by putting the information that you can join spectators more prominently

>A warning seems better than putting them into a prison they have to escape from.

A warning is a good idea but right now we put players in a prison on most maps anyway. I don't see how it would be  different here

> Edit: An alternative with accounts would be to track whether you finished a short map that acts as a noob filter. Then you only have to finish it once and can join the harder servers afterwards. (Not sure I like this solution either though.)

Yes, still I am not sure which problems accounts can reliably solve. Blockers and spammers? If accounts are optional this won't work if they are mandatory it will not work either unless there is an external identification system (like passport copy or Post ident). Ok this is offtopic.

And I don't like replys that consist of only "I don't like this (either)" Please add arguments or rather don't answer at all. If you agree to the statements of another person
like their post.

**Comment by kamillentee** [comment]
So I want to share a video of an existing multiworld server. Serverchat and scoreboard are global while map, gamemode and settings are local. No client modification needed (if you don't count 0.7 as a mod :))
https://www.youtube.com/watch?v=7VxLZ3kie4Q

A system like that should solve all the problems from above. But it creates at least one new problem: the scoreboard is not really made to display more than 64players.

**Comment by Learath2** [comment]
I don't see many of your initial problems as problems:

- Players that don't fit the difficulty level struggling at the noobfilter is mostly not even an annoyance since the noobfilter is usually solo

- 64p servers are large enough that we raaarely run into the slot issue and usually only on multeasymap and the massive t0 maps which you aleady want to let noobs play (and the solution to this problem(/the afk problem) already exists, we could enable the afk check if the server is too full)

- Older maps that lack a noobfilter lack one because the mapper decided they don't need one or they didn't want to map one.

- Having to redo the noobfilter after killing is actually a valid issue we could look into a death checkpoint tile to fix this if the mapper wants to allow you to skip it.

- The whole idea of #3486 (and noobfilters themselves imo) is to help new players figure out that a map is way above their skill level. If you don't want to carry new players then don't a lot of us mostly don't mind.

All of the above is why I don't think this is a good idea but the last piece is what kills it IMHO: The **technical undertaking**

#  Multiworld:
Naively implemented they will have huge performance implications for our relatively low powered servers. If you get more clever with your threading this could be avoided but it takes a lot of technical effort to get this right (see how many iterations even the sql code went through being a very simple 1 producer n consumer scenario or the even simpler 1p1c http code)

# Separate servers:
If we decide to implement this with separate servers that's less technical work but it either creates a rather large UX issue (the player needs to figure out that he needs to go play on a noobfilter) or creates a medium security issue (letting servers force clients to connect to other servers)

# Summary/TLDR:
This is a massive undertaking trying to solve problems that I don't think exist or are already solved (or can be solved with much less effort). Given I don't see any of the current developers willing to work on it nor any of the current maintainers willing to implement/merge it, I think this is likely not happening.

Hopefully this is comprehensive enough

**Comment by kamillentee** [comment]
I very much appreciate your detailed answer. It helps very much


>     * Players that don't fit the difficulty level struggling at the noobfilter is mostly not even an annoyance since the noobfilter is usually solo
> 
Ok I was mostly thinking of maps that lack a solo filter. Zadrotos maps even when oldschoold are examples of that. But I have another easier solution for that: #3685
I see that I forgot to add that you can use the same noobfilter for multiple maps. You would do it once only and if you play similiar diffculty level or easier maps you can just connect (until ip+name changes). 

>     * 64p servers are large enough that we raaarely run into the slot issue and usually only on multeasymap and the massive t0 maps which you aleady want to let noobs play (and the solution to this problem(/the afk problem) already exists, we could enable the afk check if the server is too full)
> 
Good

>     * Older maps that lack a noobfilter lack one because the mapper decided they don't need one or they didn't want to map one.
> 
I doubt that. If you play oldschoold almost all maps got hard filters because there alot of bad players back than. Then the years after the playerbase was getting older and even shrinking slowly while only a few new players joined. That led to the thinking filters are useless as everybody could master them anyway. For Stronghold on the other hand I guess it was meant to not have a filter.

>     * Having to redo the noobfilter after killing is actually a valid issue. We could look into a death checkpoint tile to fix this if the mapper wants to allow you to skip it. Maybe even have it in our mapping rules that you should be able to skip it if the community wants it.
> 
Good
 
> All of the above is why I don't think this is a good idea but the last piece is what kills it IMHO: The **technical undertaking**

I was kinda aware of that, still I like to share the idea just to collect everything at one place. I agree with you conclusion.

Summary of all the new ideas/conclusions

- Warn new players on hard maps, based on what maps they finished already. Lead them to better maps/tutorial map that explains the techniques required
- Death checkpoint tile so people need to do the filter only once
- Maybe autokick afk people on full servers
- allow people to join team0 at any time
