### ISSUE TITLE
Top5

### ISSUE THREAD

**Issue by Learath2** [ddnet/ddnet#3698]
It seems players really want top5 to behave as it used to. My concern with moving the new regional board to a new command was that it wouldn't have the exposure, but I think we could use the finish messages to let people know how they ranked in the regional board to promote the feature and keep top5 global.

This should make everyone happy without completely hiding the feature and in the future I think we mostly agree that this should be a UI element anyway so it should be a decent compromise while we work on the UI

@houseme-kyle

**Comment by def-** [comment]
My proposal is to just keep the old top5 as it was since it is not that discoverable anyway, so new players won't notice, old ones can keep using them. For rank we can keep the current version, otherwise there is no easy way to check the rank someone else has on this server.

As a replacement for new players add something like a second page to scoreboard that shows a nice overview with top5 global, local, team global, team local, your rank, teamrank in there and maybe the content from mapinfo too. But that needs a separate message and someone to work on it. I guess we need someone who can create a nice UI in the code for that.

**Comment by Learath2** [comment]
I can implement it if someone designs it

**Comment by houseme-kyle** [comment]
We need to be careful with the channels in which user feedback is taken. Discord is a good source but is heavily skewed towards experienced players and specific communities. 

For example, most of the recent complaints have been from GER servers and players in the top 20. To put that into perspective, they should only be impacted by this in <5% of maps and in those cases, the impact is that they see 2 fewer results. Whereas, on the other end, the community as a whole may have actually received it favorably. To take this to the extreme, there is a possibility that it is was so well received by the CHN community (the largest) that it resulted in yesterday's 8% growth. 

I am not saying this is the case and certainly doubt it had any impact on growth. However, the point is more around getting balance feedback when deciding on the viability of an idea and the danger of not doing so. 

I'll look into ways to try to sample the community at large to get an objective understanding - for this and other decisions. It is likely that the results will mirror that of the voices in discord, but it is important to validate it.

**Comment by edg-l** [comment]
> We need to be careful with the channels in which user feedback is taken. Discord is a good source but is heavily skewed towards experienced players and specific communities.
> 
> For example, most of the recent complaints have been from GER servers and players in the top 20. To put that into perspective, they should only be impacted by this in <5% of maps and in those cases, the impact is that they see 2 fewer results. Whereas, on the other end, the community as a whole may have actually received it favorably. To take this to the extreme, there is a possibility that it is was so well received by the CHN community (the largest) that it resulted in yesterday's 8% growth.
> 
> I am not saying this is the case and certainly doubt it had any impact on growth. However, the point is more around getting balance feedback when deciding on the viability of an idea and the danger of not doing so.
> 
> I'll look into ways to try to sample the community at large to get an objective understanding - for this and other decisions. It is likely that the results will mirror that of the voices in discord, but it is important to validate it.

We could implement a cross-server poll (preferably translated per server) command that writes votes to a database by unique ip and vpn/dnsbl/proxy blacklisting and take into account % of bias due to trolls using multiple ips.

Meh, now that i think of it sp someone would troll this 100%

**Comment by Learath2** [comment]
*cough* accounts *cough*

**Comment by houseme-kyle** [comment]
I did a manual attempt at getting data. Went into various servers "Survey Bot" and posted the following:
- Hi there! I am Teeworlds friendly community bot. Here to find out what features players like and don't like. 
- **The current topic is on the latest change to /top.**
- On a scale of 1 to 5 how much do you approve of the change to /top. 0 for indifferent :)
- Please message in chat or /w me. Any feedback is appreciated!

People thought I was a troll or answered "No English".. wasn't too successful. 

Got 4 responses though all from USA with an average of 4. Almost useless with that sample size. I'll try to think of alternative approaches that might get more participation.

**Comment by def-** [comment]
> I'll look into ways to try to sample the community at large to get an objective understanding - for this and other decisions. It is likely that the results will mirror that of the voices in discord, but it is important to validate it.

I don't think we should get better data on this. Seems like improving the features so that they are good for everyone is more useful than to accurately measure which of 2 existing approaches is better.

**Comment by houseme-kyle** [comment]
I agree and ideally, there is a quick solution to it. I also don't care that much about the feature. It is more about the principle at this point and a framework for making decisions. I am worried that the current approach magnifies a few voices rather than knowing the broader community sentiment. Over and above that, there are even cases when a decision is unpopular but the results show otherwise. Take Dota 2 as a hypothetical, the subreddit might be outraged about a hero change and say he is boring now but the hero ends up getting played more often.

To me, a better Teeworlds example is what happened with the outcome of Strong. The vast majority of new players and many moderate players don't understand the mechanic. It is a hidden feature that doesn't make much sense and requires you to /spec to fix it. Yet it was reverted. 

Disclaimer: I wasn't part of the Strong fiasco and the above may very well be an oversimplification. 

It doesn't mean we have to build-out tracking to allow for data-driven decisions. We simply need to be cognizant of the bias.

**Comment by houseme-kyle** [comment]
> I can implement it if someone designs it

When you mean design it do you mean as a mock-up? Because I am happy to give that a go! Will be low-fidelity though.

**Comment by Learath2** [comment]
Yes a mock-up should be good enough but even with that it'll take a while. Maybe in the meanwhile lets do what @def- suggested with top5 being old top5 and top staying like this.

**Comment by def-** [comment]
I think it's ok as it is now, let's not change things around too much for no reason.

**Comment by houseme-kyle** [comment]
@Learath2 you might have missed it but there was an update to it yesterday. Now /top shows the global top 5 always.

**Comment by kamillentee** [comment]
#3655 reference for future visitors

**Comment by edg-l** [comment]
I think this issue is solved
