### ISSUE TITLE
scoreboard blank box

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#3702]
![image](https://user-images.githubusercontent.com/69405348/111013540-6a1aaa00-8365-11eb-9cae-6e1189e7902d.png)
This block is usually blank on ddrace servers, maybe don't display it if it's blank?

**Comment by kamillentee** [comment]
Maybe use the space to show more spectator names. It's very rare nowadays but in different gamemodes almost the full server is spectating for a time. If the server allows 64 players, you cannot see all players. 
#1673 wants to use it as the weapon bar btw

**Comment by luk51** [comment]
https://github.com/luk51/ddnet/tree/feature-no-scorelimit-box
I tried to solve this by getting the CurrentServer gametype in the hud component and only show the box when the client is not int ddrace (tested with fng).
Unfortunately there is a lot of changes in the code because of visualstudio (i compiled with msvc) or because of vscode. I don't know how to turn off linting or whatever digged through all the code.

**Comment by luk51** [comment]
![screenshot_2022-06-12_21-55-36](https://user-images.githubusercontent.com/4086396/173251094-07db117f-13ac-42ca-a44f-eb20d3941bc7.png)
![screenshot_2022-06-12_21-55-49](https://user-images.githubusercontent.com/4086396/173251096-aa033b26-be80-4313-b75a-e9341d71b363.png)

**Comment by luk51** [comment]
ahh, okay 💡
