### ISSUE TITLE
/swap without command if team only has 2 players

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3737]
@houseme-kyle do you think you could implement that?

Also, should we maybe lower the 3 minute time and allow it in team 0? Feels like at the moment the feature is so annoying to use that /save and /load is easier.

**Comment by Jupeyy** [comment]
in team 0, play a map that is very long and u get free finish swap

**Comment by def-** [comment]
Same as with changing names or using /timeout.

**Comment by Jupeyy** [comment]
Ah so you get the time the person has?
save doesnt work in team 0, so this wasnt clear to me^^

**Comment by houseme-kyle** [comment]
@def- Do you mean swap without name? Could be looked at.

1) I'm open to lowering it. Was a suggestion made on the other thread though as people were worried that new tees won't be given a chance on a part. The use-case is for scenarios where one player is stuck for minutes on end. 

Maybe 1 minute?

2) Still hesitant for allowing it for team 0. I see that /swap isn't widely available yet. Think we should give it some more time being live before we extend it. 

What I can do is extend the window because right now it is very short (30 seconds).

**Comment by kamillentee** [comment]
> 
>     1. I'm open to lowering it. Was a suggestion made on the other thread though as people were worried that new tees won't be given a chance on a part. The use-case is for scenarios where one player is stuck for minutes on end.
> 
> 
> Maybe 1 minute?
> 
3 Minutes is the cooldown or the waiting time? Waiting time should not be longer as the time a /timeout swap takes. What I was originally thinking about is the situation of a hammerhit map where the worst player is the last one alive. 1 Minute or 100 seconds is enough to discourage the usage of /swap in most cases there.
 Cooldown can be longer, it mainly prevents many swaps in a short period of time. 


>     1. Still hesitant for allowing it for team 0. I see that /swap isn't widely available yet. Think we should give it some more time being live before we extend it.
> 
Why? The only reason that is constantly brought up against it is not important (swap to give finish to others), If nobody can name any other reason /swap should be allowed in t0 too.

**Comment by Jupeyy** [comment]
Before opening a new issue, since its also /swap related, and i dunno if you aware of it.

If you in a team with multiple ppl, it only adds the penality to the swapped ppl, not the other ppl. And atleast when i tested it, using /save /load resets them for all(tho i didnt really look to which time), so maybe a bit inconsistent rn?
