### ISSUE TITLE
Bug: Mute Players (client) doesnt save

### ISSUE THREAD

**Issue by trafilaw** [ddnet/ddnet#3756]
If you mute someone at the client and you leave the server, it doesnt save.
So you have to mute them everytime again and again...

**Comment by heinrich5991** [comment]
Does the player change name/clan when they do this?

**Comment by trafilaw** [comment]
No changes

**Comment by trafilaw** [comment]
@heinrich5991 https://i.imgur.com/nMzqpkM.gif

**Comment by kamillentee** [comment]
I think its a feature not a bug. You may want to mute someone for some time but you will forget to unmute later. 
I know there are problems with spamtrolls but the client mute  does not work to good against them as they often change their name very often in a short period of time.

**Comment by def-** [comment]
> I think its a feature not a bug. You may want to mute someone for some time but you will forget to unmute later.

Exactly. There is an add_foe command in f1, but I don't think it should be too easy, otherwise you'll end up having muted half the server at some point :D

**Comment by trafilaw** [comment]
Hm, the add_foe command is good, but at some point if the dude has special characters you cant type it :P

**Comment by def-** [comment]
True, we need a name completion in f1 for that.

**Comment by kamillentee** [comment]
> True, we need a name completion in f1 for that.

For reference #1489

And if we could work with player IDs for such commands it would be even better.

**Comment by Kaffeine** [comment]
> Not saving muted players is intended

Apparently (from the issues and players feedback) it hurts UX, because there is no hint that the mute is ephemeral, and no hint that there is a way to mute permanently (`add_foe`).

---

> You may want to mute someone for some time but you will forget to unmute later

Or you may want to mute someone forever and (as a normal player/user) <s>curse</s> blame the game because

> you have to mute them everytime again and again...

---

> I don't think it should be too easy, otherwise you'll end up having muted half the server at some point :D

We can add mute indicators to the players list (scoreboard). One extra character next to the player name won't hurt as much as the "bug: mute players not saved".

It may sound inessential for ddrace gametype with many players trying to finish different maps on tens servers. But there are other mods (e.g. FNG) with few servers where you meet the same players all of the time.
