### ISSUE TITLE
Hook is reset on swap

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3765]
Ideally, hook should be kept.

**Comment by heinrich5991** [comment]
CC #3764.

**Comment by def-** [comment]
@kyle-bradley

**Comment by kyle-bradley** [comment]
Most use-cases of /swap will be fine to not keep hook state. Due to the previous exploit, I wanted to be on the safe side and reset it for all tees. For example, the tee that is being swapped could be hooked on an external tee and have that kept locked for extra drag. 

The solution could be to check the hook target against the swap target but didn't feel it was needed for the first (exploit-free) version.

**Comment by C0D3D3V** [comment]
implemented in #5049
