### ISSUE TITLE
Enable /swap for team 0

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3801]
@kyle-bradley I don't see a reason not to have this. It's basically the /timeout swap but a bit easier.

**Comment by heinrich5991** [comment]
I feel like you should know a reason not to have this, we had a long discussion about it when it was implemented for teams:

It makes it trivial to swap, it encourages people to swap where they would have otherwise tried themselves.

I recently played Back in the Sky with a lot of people, and more and more people tried to save a stuck tee and got stuck themselves, until a final tee remained. If there had been /swap, I'm pretty sure the tee wouldn't have tried themselves, but rather swapped with murpi. I don't think this is a good outcome.
