### ISSUE TITLE
Command to get to a specific zoom level directly

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3923]
Probably `zoom <level>`?
Suggested by M Emile ingame.

**Comment by def-** [comment]
`bind x "zoom; zoom-; zoom-; zoom-; zoom-; zoom-"` :D

**Comment by MEmileTW** [comment]
What I mean is a simpler way to do this: 
"toggle cl_default_zoom 10 3 ; zoom"
With this specific way it's a pain to give to others because it messes up your default zoom so you have to tweak it depending on your current one, then you can't use your "zoom" bind to reset unless you change it to "cl_default_zoom 10; zoom"

**Comment by heinrich5991** [comment]
@MEmileTW Do you want to have a way to use `toggle` with `zoom`?

**Comment by MEmileTW** [comment]
@heinrich5991 that's exactly the purpose of the bind i cooked up, mainly so it's easier to look around in the middle of a gores section. It works okay-ish but having zoomX would be much better in terms of sharing it to other people since "toggle cl_default_zoom 10 3 ; zoom" needs to be adjusted if your default is not 10 usually.
