### ISSUE TITLE
DDNet freezes when going into select mode in the console on Windows

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3925]
https://www.youtube.com/watch?v=--IRLg3bkao

Apparently you can simply go into select mode, then when DDNet tries prints something, it freezes. If you have DDNet in fullscreen mode, you apparently can't go out of the select mode anymore, in windowed mode the fix works, apparently.

I'd guess that this is done by Windows and that we can't do anything about it.

Any Windows gurus that can chime in? :)

Reported to me by M Emile.

**Comment by fokkonaut** [comment]
https://community.rti.com/kb/windows-console-seems-freeze-dds-application-when-clicked

**Comment by Learath2** [comment]
I'm guessing the hang happens at `WriteConsoleW`, can we check if re-enabling aio fixes this? If re-enabling aio on stdout still fails, we can try writing a new logger that uses `WriteConsole` but inside the `aio` thread, so it doesn't block the main loop.

**Comment by BloodWod-513** [comment]
It seems to me that the console freezes on purpose, because if everything was moving, it would be inconvenient, probably, I can't say. Maybe it is possible to somehow get information that a person begins to "mark" or "copy", and at this time it is written to the log, and the call of the write method to the console is not called, after which all this will be written to the console? In any case, if you specifically stop the console for a long time, there will be a problem
![qedit](https://user-images.githubusercontent.com/33897884/127137479-b99f8113-717e-4b01-bcab-510cb07a1ae9.jpg)

**Comment by Learath2** [comment]
It does freeze on purpose. What I'm saying is it doesn't need to also
freeze the main gameloop. It just needs to freeze console output

**Comment by Robyt3** [comment]
This already works when using `CLoggerAsync` on Windows, but then we don't support colors in the console.
