### ISSUE TITLE
unable to open audio: No available audio device on Solus linux

### ISSUE THREAD

**Issue by mahdiG** [ddnet/ddnet#399]
Hi. I'm on Solus (a new linux distro). I have sound out of the game but when I open DDNet it says: The sound device couldn't be initialized.

**Comment by Laxa** [comment]
Hello, I think this is more an issue of SDL 1.x rather than ddnet.
You could try to see directly on SDL website. Note that SDL 1.x might not be supported anymore.
DDNet is planned to be released some day on SDL 2.x, you could try to compile and run the SDL 2 branch from DDNet to see if that works better, keep in mind that this branch has never been released and might have lots of bugs.
