### ISSUE TITLE
Hover tooltips for misc. things

### ISSUE THREAD

**Issue by kaitlynia** [ddnet/ddnet#4212]
Just thought of some practical uses for hover tooltips:

1. Hovering a friend in the Friends tab would display the highlighted server info normally seen in the server list (as some compact string)
2. Hovering a server in the list would display a list of players connected (probably displayed as columns of names, or possibly show a mock-up of the in-game player list)
3. Hovering options in the settings pages could display helpful explanations for them
4. Same as the above but for the editor and demo viewer controls

This could be optionally disabled or we could just show the tips if ctrl is held. Best option in my opinion is to serve this as a multi-value setting like cl_hover_tooltips (0 = disabled, 1 = shown when ctrl is held, 2 = enabled) and make 1 default.

**Comment by C0D3D3V** [comment]
> Hovering a server in the list would display a list of players connected (probably displayed as columns of names, or possibly show a mock-up of the in-game player list)

![image](https://user-images.githubusercontent.com/14315968/158808062-b17628ef-ea85-4262-8c0f-c372c7a7d0f7.png)
We already have this information in the Server Details/Information tab (as you can see in the image), do you still want to show this information when hovering? 

In Teeworlds 0.7.4 the information is displayed in the list itself, which I actually find quite handy, but our version is also good, only then you can not simultaneously display the server info and filter or friends tab.
https://www.teeworlds.com/?page=journal&id=13348

If we would show the server info also in the list instead of on the side we could omit the tooltip at the place, do you find a tooltip nevertheless more practical for this?

**Comment by Robyt3** [comment]
We've added various tooltips.

> Hovering a friend in the Friends tab would display the highlighted server info normally seen in the server list (as some compact string)

You can click the friend to reveal the server.

> Hovering a server in the list would display a list of players connected (probably displayed as columns of names, or possibly show a mock-up of the in-game player list)

Should not be in a tooltip.

> Hovering options in the settings pages could display helpful explanations for them

Done.

> Same as the above but for the editor and demo viewer controls

Done for demos. Editor controls always had tooltips.

> This could be optionally disabled or we could just show the tips if ctrl is held. Best option in my opinion is to serve this as a multi-value setting like cl_hover_tooltips (0 = disabled, 1 = shown when ctrl is held, 2 = enabled) and make 1 default.

No.
