### ISSUE TITLE
Remaining unicode windows problems?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4301]
Nakimar on Discord reports:
> the red sign is gone, the servers are working but the skins and texture packs are not loaded

@Robyt3 is it related?

**Comment by Robyt3** [comment]
I'm not sure if I understand Nakimar correctly, but I suspect that all textures loaded from paths containing unicode fail to load (will be displayed as white only), because we are using pnglite's `png_open_file` which internally uses `fopen`, which cannot handle multibyte unicode paths on windows.

By the looks of it, libpng (#3407) should work with unicode paths, as the images are loaded from memory after using our working `io_open` and `io_read`. Might be possible to hotfix it with pnglite by opening the file with our `io_open` and then calling `png_open_read(png, 0, fp)` (or `png_open_write`) with that file pointer `fp`. The preceeding argument 0 should make pnglite use the default read/write callback, which should work once it has the file handle.

**Comment by def-** [comment]
Yes, that hot fix would be great, since I don't how long until we can get libpng in and that would be another major release.
