### ISSUE TITLE
Editor mouse3 move with GUI hidden (TAB)

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4553]
It's not possible to hold mouse3 and move the map endlessly to the left or up anymore. Only down and right works.

**Comment by Robyt3** [comment]
Works for me. On which map does this happen for you?

**Comment by Marmare314** [comment]
I could reproduce it on 'Sunny Side Up'. It occurs because when moving the mouse to the right/lower border its not inside the editor view anymore.

I think this happens because the check if a point is inside a rectangle is asymmetrical:
```C++
bool CUIRect::Inside(float PointX, float PointY) const
{
    return PointX >= x && PointX < x + w && PointY >= y && PointY < y + h;
}
```

Changing '<' to '<=' fixed the issue for me. But I am not sure if this introduces bugs elsewhere.

**Comment by Robyt3** [comment]
@def- The underlying functionality was changed in #2869. Do you remember what kind of issue this was solving?

**Comment by def-** [comment]
When you were close to two fields you could hover and select both at once
