### ISSUE TITLE
Free view + solo + /specteam = dont see anyone

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4646]

**Comment by WatermelonDriveway** [comment]
I've reported this a few times in the discord but it's mostly gotten buried.  Been meaning to post it here.  Here's the example I posted.

https://u.teknik.io/cM8BQ.webm

"So yeah, you can see me toggling /showothers and /specteam in the bottom left there.  /specteam being on makes your teammates in solo parts disappear when in /pause - the state of showothers doesn't matter.  The benefit of using /specteam is so when there's a million tees on the map, you can use /pause to check your teammates progress without seeing everyone else. This just doesn't work if they're in a solo part.  If you want to see their progress you have to see every other tee in every other team as well.  Maybe this is intentional?"
