### ISSUE TITLE
feature-request: point indicator ingame

### ISSUE THREAD

**Issue by 1uk** [ddnet/ddnet#4855]
Hi,
I play ddnet for some time on and off and did not manage to get a good rank. (about 200 points)
For me it would be nice to have a point indicator in the game. Like in minecraft:
<img src="http://www.minecraftmods.com/wp-content/uploads/2015/07/HUD.png" height="200px">

#### motivation
This is not to make beginners feel more intimidated, and make tw more apart, but to motivate people like me
to get points. (I just stick around at the beginning of brutal maps).

#### other / following ideas
* have a wikipedia base of map recommendations similar to a 'quest guide': [optimal quest guide](https://oldschool.runescape.wiki/w/Optimal_quest_guide "runescape")
* have a wiki article for popular maps about the parts, and the skills you need, and what dummy maps... eg. you could play to prepare for it.
* map tree -> like an achievement diary: complete cobra series, then complete this series and so on, so that you get **map recommendations** based on your skill level (the maps you already have finished, or the points you have earned).

#### images
**map recommendations**
<img src="https://i.pinimg.com/originals/34/dd/db/34dddbbc7b75a66790c4e977e28fac24.png" height="200px">
**hud point indicator**
<img src="https://www.minecraftmods.com/wp-content/uploads/2015/07/HUD.png" height="200px">
**point indicator for others**
<img src="https://i.ytimg.com/vi/fdStDgcC1B0/maxresdefault.jpg" height="200px">
**points indicator browser**
![points_browser](https://user-images.githubusercontent.com/4086396/159259817-f8b2daa6-b412-4cd3-8f79-ab882884c3c9.png)
**points in_game**
![points_ingame](https://user-images.githubusercontent.com/4086396/159259862-1d044f16-fba6-4a7c-86c0-889c7776b751.png)

**Comment by def-** [comment]
I feel like the existing DDNet point system might already be causing some people to get addicted, so I wouldn't want to add more to that. In general I don't like these gamifications much to encourage people to have a "streak" (aka addiction) or prominently display their points so they collect more for their social standing. The game itself, the maps, and interactions with the community should be what interests people and motivates them to keep coming back.

**Comment by C0D3D3V** [comment]
It all sounds like very good gamification suggestions that a profit-oriented company would certainly implement.

We already have something like a guide that is supposed to lead the players from few skills to more. That is our points system for the maps, easy maps give few points and are in the category Novice to find, heavier are in the category Moderate, then come the Brutal and finally the Insane maps. The system is unfortunately not very granular and does not give information about what skills you need to know to be able to finish a map.  Would be really good to have such a recommendation system that does not necessarily include all maps just some recommendations to learn certain skills. This could be added to the wiki, although it is always very subjective what is a suitable map to learn something, a few good maps for certain skills would probably be enough. Consistency then comes through the many practice. 

>  and what dummy maps... eg. you could play to prepare for it.

I rather have the feeling it's the other way around, because dummy maps often require more skills than team maps, because you have to do everything alone.

**Comment by 1uk** [comment]
Thanks for your feedback! I might contribute to the ddnet wiki and make some articles about maps. Will need proofreading though.
Eg. Maps like Stronghold, Simple Down, Multeasy and so on (you know the maps better than me) deserve their own wiki article. imho
