### ISSUE TITLE
Player in "Your team has 1 player that has not started yet" is wrong

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4884]
As reported by cheeser0613. Seems to happen with large teams
![unknown](https://user-images.githubusercontent.com/2335377/159911292-f17a6682-6550-46ff-8d3a-5e6f20f10071.png)

**Comment by def-** [comment]
The code looks correct to me, not sure why this would happen in a very large team.

**Comment by C0D3D3V** [comment]
The question is how sure he is that it really was a false report. It would have been better if he had included the demo. 
I had also once thought to have seen such a false message in a large team, but I think it was a correct message but from the round before and in the mean time the team has killed and restartet (fast because of faily first part) (without lock).

**Comment by C0D3D3V** [comment]
I took a closer look at the screenshot. The team has already started 40 seconds and every 30 seconds comes the remainder so it is not 10 seconds ago that the message was issued. probably he has just finished the noobfilter is but not yet through start.

**Comment by C0D3D3V** [comment]
However, the message always outputs only one player because there is a break in line 280 https://github.com/ddnet/ddnet/blob/c9f462b70d121735eda8d0ff2bec16f5ff1d717e/src/game/server/teams.cpp#L280 (the steing buffe would also not be large enough for more player names).
