### ISSUE TITLE
DDnet Client on borderless window

### ISSUE THREAD

**Issue by Ryozuki** [ddnet/ddnet#504]
I think this started on one of latest updates.

On windows (10) when you want to switch screen on borderless window i used to alt tab and then click on the right bottom, that puts you on your desktop, but now it's impossible. DDnet wants to stay there.

**Comment by FallenKN** [comment]
If I recall correctly a window will be focused aslong another window wants your Operating System to focus on it.
Since your Desktop isn't really an application it wont try to get your focus over the borderless window.(borderless windows behave a little bit different to normal windows)
So if you want a shortcut to your Desktop press Win+D or use a bind to minimize: bind [key] minimize

**Comment by Ryozuki** [comment]
It's weird, when i press win+d it focuses on the desktop. But teeworlds it's still over it. Even if when i click, it interacts with the desktop and not the client that is being showed on screen.

**Comment by FallenKN** [comment]
If you press Win+D you should be able to interact until antoher widow will open and then Teeworlds will move to thw background with your new window on top of it as far as I know.
Rather bind minimize command for using borderless window.

**Comment by Ryozuki** [comment]
it doesn't work. AGAIN The problem is that teeworlds don't move to the background and i can't see the desktop but i can interact with him.

**Comment by FallenKN** [comment]
Cant reproduce this, for me its just fine. On which version of DDNet are you?

**Comment by BannZay** [comment]
For me Teeworlds can be minimized only if it have not exactly your screen resolution + borderless.
Solution for me is just do not use borderless at all
