### ISSUE TITLE
Ghost ninja shield appears while shooting?

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5047]
Reported by [Voxel#6729 on Discord]():
> not sure if this was reported but im using nightly 20220430
> ![image](https://user-images.githubusercontent.com/366230/166084135-c0f102bd-161c-481f-8993-d6c2f3a66a19.png)

Very likely related to #4728.

**Comment by C0D3D3V** [comment]
seems like the muzzle sprite is bigger and overlaps with the new shield ^^

**Comment by C0D3D3V** [comment]
Next to the pickup shield and the new shotgun shield would still be space for the ninja shild.

what i also noticed, the new shields don't match the design of the old pickup shild, rather the one of the HUD life display. 

Would also be generally worth considering to put this in a ddnet_game.png, because it makes no sense in teewlrds to have shields for individual weapons. so this is very unlikely that teeworlds wants to adopt the new game.png. Then we could also use graphics that make sense, instead of putting e.g. Schotgun shot on a sign, you could cross out the Schotgun on like a no passing/no parking sign.

Then we would also have the game.png clean if at one point teeworlds gets new features we also want to import. Like the water PR https://github.com/teeworlds/teeworlds/blob/5c5b54c8eb00ac70c4eb1bd09b74554a0c865bdc/datasrc%2Fgame.png  maybe there will be a PR that overlaps with the shild slots...

**Comment by def-** [comment]
@C0D3D3V sounds good, but how long until your HUD change is ready? This should probably be released soon, don't want to leave it broken for a while.

**Comment by C0D3D3V** [comment]
you could already use the hud.png ravie created and then I update it as soon as my PR is ready 
https://github.com/C0D3D3V/ddnet/blob/New_HUD/data/hud.png

I try to finish it up today... so you could also wait for tomorrow... It is also only broken in nightly, or can steam player now also play nightly?

**Comment by def-** [comment]
Yes, Steam also can use nightly: https://ddnet.tw/news/nightly-build-revived/
