### ISSUE TITLE
feature request: bouncy blocks

### ISSUE THREAD

**Issue by l-ouis** [ddnet/ddnet#5124]
i'd like to propose a new entity solid block, called a bouncy block:
it would behave as an "ideal trampoline", mirroring the velocity of any tees or projectiles (grenades mainly) that touch it.

if people are interested in this, maybe we can discuss it further. some things to discuss:
how it interacts with hook
how it interacts with weapon shots
sounds (i could do this part)

PS: im willing to chip in $5 for a dev to work on this if people think its a good idea

**Comment by C0D3D3V** [comment]
I like it
> how it interacts with hook
It could be placed below/above hookable/unhookable blocks so it just adds the bouncy property to the block.

> how it interacts with weapon shots
Intuitively, I would say should only granades bounce off of it. All other weapons behave like with other solid blocks.

**Comment by fokkonaut** [comment]
If a hook touches it, it should get bounced aswell.

**Comment by C0D3D3V** [comment]
o.O

**Comment by ChillerDragon** [comment]
> It could be placed in front of hookable/unhookable blocks so it just adds the bouncy property to the block.

What is the difference between a bouncy hookable and a bouncy unhookable?

**Comment by C0D3D3V** [comment]
If you hook it you could increase your fall down speed, that then get on bounce inverted.

**Comment by l-ouis** [comment]
how about making them hookable by default but giving it a weaker hook than hookable? to fit with the "slime" aesthetic

**Comment by heinrich5991** [comment]
Is there some game you drew inspiration from? How can I find out if it'd fit DDNet physics?

**Comment by C0D3D3V** [comment]
So I find the idea of a reflective hook interestung, but does not necessarily fit the idea of a trampoline or slime. With a slime I would rather think that the hook becomes slow, so really slow. So that it almost doesn't pull the tee to itself. And with a trampoline, the hook would either not grip ^^ or tear the jumping sheet. 

I can come up with a prototype, the bouncing block without the hook shouldn't be too hard to implement, the hook is probably the hard part.

**Comment by C0D3D3V** [comment]
perhaps the slime would also hold the hook longer than normal because the hook also retracts more slowly ^^ Would even be harder to implement.

**Comment by l-ouis** [comment]
heinrich: minecraft slime blocks is a good example. i think its a simple enough concept to fit ddnet

codedev: i like the idea of hook not lasting forever and having a lesser pull strength

**Comment by heinrich5991** [comment]
> minecraft slime blocks is a good example.

As far as I can tell, Minecraft slime blocks aren't ideal trampolines. Do you want them to be ideal?

Things one has to decide, not necessarily right now in the next answer: How do you bounce off if you only hit part of the tile? How do you bounce off in the "corner case"?

**Comment by C0D3D3V** [comment]
If we just invert the velocity vector, it will probably also not be an ideal trampolin, because how gravity works in teeworlds. But it would probably be way more bouncy then minecraft slimes. We would have to wait till we have a prototype, to define the details more clearly. 
If you bounce on the sides I would invert the x velocity, otherwise the y velocity, so I would not change the angle of the velocity vector depending on the propotion you have contact with the block, that would make the physic way more harder to control. But we can test it out as soon as we have a prototype.

**Comment by heinrich5991** [comment]
This seems to be comparatively easy to code, I'd probably do a community vote after someone creates a proof of concept, so we can actually see it live.

**Comment by fokkonaut** [comment]
Couldnt we add a tune parameter for bouncyness, so it applies in some tune zones? The tw code itself has bouncyness on blocks already, all sides, would just need to get cleaned up and probably smoothened a bit.

**Comment by Chairn** [comment]
I think we need to set up a list of prerequisites for new ideas to be included and to also ask the community in general. (see also https://github.com/ddnet/ddnet/issues/4651)

**Comment by AssassinTee** [comment]
https://github.com/teeworlds/teeworlds/pull/3068#issuecomment-1140327500

Bouncyness is already implemented into standard teeworlds and is missing a tuning variable. All you need to do is add the mentioned PR and use a tuning layer. This already worked with other materials (like ice), too!

**Comment by C0D3D3V** [comment]
Yes we have tune layer. But that is a other stroy ^^ adding the elasticity parameter would be ok for the moment, and would allow mappers to already to test out the pysics. But currently tunig layer is kind of bad predicted, leads to strange visuals in the client sometimes.

Also we have a lot of players mainly playing with entities. So having a fixed set of blocks with knowing physics would improve gameplay and entities (the player would not see the blue tuning tile but a slime entitie or somthing like that) also mappers would not need to know all tuning parameters, but can select materials with known physics.

**Comment by AssassinTee** [comment]
Note for me: When implementing check GroundJumpImpulse. You might get crazy jump physics otherwise xD

**Comment by AssassinTee** [comment]
@l-ouis you can now create bouncy blocks by settings the `ground_elasticity_x` and `ground_elasticity_y` tuning variables either for the map or in a tuning layer. The maximum value for both is 1.0, but you can also use half values like 0.5 in order to reduce your bouncing strength. This feature is currently only available in the master and with an older client you might have a prediction issues and it will take some time for the rollout, but it should be available with the next release

**Comment by l-ouis** [comment]
> @l-ouis you can now create bouncy blocks by settings the `ground_elasticity_x` and `ground_elasticity_y` tuning variables either for the map or in a tuning layer. The maximum value for both is 1.0, but you can also use half values like 0.5 in order to reduce your bouncing strength. This feature is currently only available in the master and with an older client you might have a prediction issues and it will take some time for the rollout, but it should be available with the next release

i just tested and it works great
1 thing - if the value is less than 1, you'll never eventually reach a stop - maybe round the velocity down to 0 at one point?

**Comment by AssassinTee** [comment]
@l-ouis you reach a stop eventually, tested it.
the double layer of tunes is a problem from the implementation of the tune zones, not of the bouncy blocks. You can open a new issue here if you want, but this happens with all tunes if you enter with enough speed.
