### ISSUE TITLE
Run Integration Tests on Windows

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5232]
@ChillerDragon A few suggestions to further expand the integration tests

1. Run the tests also on windows

~~2. Can we maybe output the output from the client/server somehow? currently nothing is output~~
![grafik](https://user-images.githubusercontent.com/14315968/170437851-d2d141d5-0199-441c-8845-8abcad2e25cd.png)

~~3. Can we do more complex processes? Can you research if you could somehow simulate inputs, e.g. test if you can hook (other tees), jump and walk.~~

**Comment by ChillerDragon** [comment]
> 1. Run the tests also on windows

I do not use windows. I do not know how windows works. I suggest a windows user looks into that.

> 2. Can we maybe output the output from the client/server somehow? currently nothing is output

I intentionally hid them. Its two clients and one server. It is plenty of output. Its just spamming the usual log messages.
In case something goes wrong it barley shows something useful in the logs. The few error messages the ddnet client or server log are usually user fuckups like chosing a invalid `sv_map` for the server and similar.

> 3. Can we do more complex processes? Can you research if you could somehow simulate inputs, e.g. test if you can hook (other tees), jump and walk.

I do plan on improving the map to cover more. Like switchers and other things I haven't thought about it yet.
For client input that becomes tricky. Automating inputs would be considered as a cheat. Especially in the client.
Manipulating the headless client to allow control inputs over fifo or similar is not something that would ever get merged in ddnet as it allows for cheating with the official client. Using external tools to demonstrate how to turn the vanilla ddnet client into an cheat client in the CI is also not too nice imo. I do have a simple [client component](https://github.com/chillerbot/chillerbot-ux/blob/f313e02fcb550cf38b7836016da4498b9a9cca84/src/game/client/components/chillerbot/stresser.cpp) in my ddnet fork that I use for testing servers. But I am not sure if something like that belongs into ddnet. Given that a simple [`eval_if`](https://github.com/ddnet/ddnet/pull/3552) console command got rejected due to cheating I do not think that an automated client input has any chance.

**Comment by Chairn** [comment]
Is it possible to hardcode keypresses in an array and just play the array with usual functions?

**Comment by ChillerDragon** [comment]
> Is it possible to hardcode keypresses in an array and just play the array with usual functions?

Yes sure. Its not that is is a technical issue. Its more about we do not want to integrate an replay bot into the ddnet client.

**Comment by C0D3D3V** [comment]
Mh, I see there is a conflict. (Even tho its not hard to implement a replay bot)... We could probably implement more unit tests, especially for inputs, and resulting gameworld behaviour. But that is another topic.

**Comment by C0D3D3V** [comment]
I close this in favor of 
https://github.com/ddnet/ddnet/issues/5691. Because this is full of comments for other toppics.

**Comment by Chairn** [comment]
Oh sorry, didn't see there was already an opened issue. Not sure we should close this one as the comment will be forgotten into oblivion :smiley:

**Comment by C0D3D3V** [comment]
For me the discussion was kind of over thats why I renamed it to only the open topic, but if you still see open questions you are free to reopen it, or open a new issue with the topic.
