### ISSUE TITLE
Shotgun pull prediction with high latency inaccurate

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#5307]
Title, after the second shot the prediction gets all messy:

https://user-images.githubusercontent.com/60477660/171548445-526c0fab-4387-4ab6-9ba6-658e69b6b4f5.mp4

fokkonaut on Discord:
> Because in the server there was a physic change in shotgun

**Comment by C0D3D3V** [comment]
I can confirm, already on a local server with prediction_margin set to 300, the lag is very noticeable (while on 15.9.1 everything is predicted fine). I'll look a little deeper to see what can be the reason.

**Comment by C0D3D3V** [comment]
probably some timing related changes, because if you hold left click with shotgun it will also look like if it spams laser to fast

**Comment by def-** [comment]
@C0D3D3V you changed the physics code on server side, but not in client prediction side I think
CC @trml

**Comment by C0D3D3V** [comment]
I do not think so... I just use `git bisect`  it.. 5 more build and I have it

**Comment by def-** [comment]
@Zwelf ^

**Comment by C0D3D3V** [comment]
@murpii  that was no real physics change... that was a math fix by deen. And I added the the broken math back in using a constant and a check for the condition (when tees are stacked). But I added it in client and server...

**Comment by def-** [comment]
Well, "math fix". Our physics was relying on undefined behavior, I fixed it wrongly, c0d3d3v fixed it to replicate the old behavior, but in a deterministic way.

**Comment by C0D3D3V** [comment]
This could also be related, why the latest client can not play on 13.2.2 server without similar lags as in the video

**Comment by C0D3D3V** [comment]
Nope the issue with the 13.2.2 server comes from a other commit

**Comment by Zwelf** [comment]
So... The input handling changed a bit. Previously the automatic weapon was only executed before the tick[[1]](https://github.com/ddnet/ddnet/blob/ce0a262b6dec42c86443f6e1dbf6dee6e56ef63d/src/game/server/entities/character.cpp#L655) if an input packet was sent for this tick. After the tick otherwise[[2]](https://github.com/ddnet/ddnet/blob/ce0a262b6dec42c86443f6e1dbf6dee6e56ef63d/src/game/server/entities/character.cpp#L715). AFAIK Input packets are normally only sent every for every 2nd tick (when there is no input change between ticks).

The new behavior is reproducible in the old code by binding the "Shooting" to the scroll-wheel and use constant scrolling to hold shotgun. The client predicts it correctly, because it knows which ticks it has sent an input packet.

One possible fix would be to update the prediction code to always apply the input from the last tick here somewhere:
https://github.com/ddnet/ddnet/blob/ce0a262b6dec42c86443f6e1dbf6dee6e56ef63d/src/game/client/gameclient.cpp#L1776-L1786

**Comment by trml** [comment]
Updating the prediction seems like the easiest fix, as I assume the change is wanted (as it makes the inputs more reliable and less dependent on how fast you press/move the mouse, and also less affected by random network lag).
