### ISSUE TITLE
Friends List Bug

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#539]
Shown here:
https://youtu.be/Hz7F3iZOO6E

You can see that the name I double clicked on was "Carl" but showed DARK instead, when I don't have DARK on my friends list.

**Comment by H-M-H** [comment]
Ok, I just had a quick look into source of the serverbrowser and it turns out all the nicks and clans are hashed for faster comparison with this function:

```
unsigned str_quickhash(const char *str)
{
	unsigned hash = 5381;
	for(; *str; str++)
		hash = ((hash << 5) + hash) + (*str); /* hash * 33 + c */
	return hash;
}
```

So gratulations @PathosEthosLogos you have found a collision for the nicks "Carl" and "DARK", which means the same hash is evaluated (2088990887) for both of them.

So the question is should we keep it like that, get a better hashfunction or just compare all the strings the hard way.

**Comment by def-** [comment]
Haha, that's cool. I also read the source code and couldn't find a bug. How about comparing the hashes first, and only doing actual string comparison when the hashes match? That should not impact performance much since we only match rarely.
