### ISSUE TITLE
Old Keyboard Mode (combined into Old Input Mode) to complement Old Mouse Mode

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#541]
I'm noticing key presses not registering, but luckily only when typing in chat. It's usually the first character. To replicate, press T and then any character as fast as you can. You'll notice that the character following the T press is not shown..... sometimes. It's kinda intermittent, but maybe I'm just not being fast enough some of the time.

I have a hunch it's related to the "old mouse mode" bug of mouse clicks not being registered (since this bug is similarly not present in ddnet 9.x).

Lastly, since the "old" input mode(s) are more reliable and work just as well, why not default to them and instead have a "New Input Mode" checkbox (unchecked by default)?

**Comment by Henningstone** [comment]
> I'm noticing key presses not registering, but luckily only when typing in chat. It's usually the first character. To replicate, press T and then any character as fast as you can.

Exactly the problem that I'm facing aswell. So it's not only my imagination.... It's annoying as hell ._.

**Comment by def-** [comment]
Ping @TsFreddie @ACTom

**Comment by TsFreddie** [comment]
I already noticed that missing keyboard input issue. Working on fixing it. 

I didn't do the mouse part. I think it is the implementation of SDL2 with hardware mouse support have some issue. I haven't encounter any missing click myself.

Another concern of mine is that I think (though I'm not sure) in game mouse is also hardware based, or received mouse input from system instead of the hardware. Mouse acceleration will be enabled depends on the system settings (most noticable on Windows with percision enhancement enabled).

Lastly, I can bring old keyboard input back, although I think once fixed the missing input. The old input and the new one havn no difference since they are going through the same SDL event for most western languages.

Old mouse input though, I'll see if there are anything I can do about event handling.

**Comment by TsFreddie** [comment]
An easy fix is killing all SDL_Start/StopTextInput. So all text input event and non-text event will be processed all together then we'll never have missing text input.

If I can't fix missing input in a short time, I might do that.
It will only make CJK input a bit awkward but still usable.

**Comment by def-** [comment]
I think this is fixed. Reopen if you can reproduce.
