### ISSUE TITLE
Joystick -> Gamepad?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5419]
@Robyt3 It seems like Joystick is the term for flight-game controllers, do we want to call it gamepad instead? Or just controller? Not sure what the best term here is.

As noticed by cheeser0613

**Comment by murpii** [comment]
Maybe Controller instead of gamepad?

**Comment by Robyt3** [comment]
I named it joystick because it's using the generic SDL joystick system. But for end users maybe Controller would be better because it's generic controller support.

I don't like using the term Gamepad right now because:
- gamepads to me mostly look like Xbox/PS controllers but we support any kind of controller device with axis, buttons and hats
- we don't support gamepads on a high level
- SDL uses the term gamepad for the higher level Gamepad API
