### ISSUE TITLE
ListDirectory should merge duplicate files and directories

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet#5496]
if you use
```

add_path $DATADIR
add_path $DATADIR
add_path $CURRENTDIR
```
as storage.cfg

or for example have custom menuimages in your config directory it duplicates everything.

It should merge directories and only show the file with higher priority (e.g. config dir has higher prio)

**Comment by heinrich5991** [comment]
Yup, also encountered this before.

**Comment by Robyt3** [comment]
For the demo and editor file browsers I think it would be better to support navigating between different storages separately instead of trying to combine the view of all storages into one. Combining storages would mean we can't load all versions of a file if it exists in multiple locations, as the highest priority file is always chosen. For the general purpose file browsers (editor and demos) we should support loading all files. The small file selectors like the assets, themes, etc. should hide the duplicate items and always use the one with the highest priority.

Here is an example how this could look for demos:

https://github.com/ddnet/ddnet/assets/23437060/e08f56cf-5912-4cf4-b345-cd72e0faf27f

The user can navigate up to the storage root with the `..` folder, which is only shown in the root folder when there are multiple storage locations with a `demos` folder.

When the storage root is selected, all storage locations that have a `demos` folder are shown as entries.

Alternatively we could add a dropdown menu or menubar over the file browser to select the current storage location.

Another question is which location should be shown initially. Currently I always show the save storage (config directory) first. The file browser could also start on the storage root location instead if more than one location is available.

**Comment by def-** [comment]
My main worry is that this could confuse users who are used to the old way of merging the folders into one view.

**Comment by Jupeyy** [comment]
For editor i can kinda understand this (even tho i also find it unlikely here). But for demos this seems weird. When would you ever load demos into your data dir and additionally have a name collision ^^

generally i think data dir should be considered read only anyway.

The main problem in this issue was indeed that i set the data dir as config dir (so i have a ddnet instance in itself)

**Comment by Robyt3** [comment]
> For editor i can kinda understand this (even tho i also find it unlikely here). But for demos this seems weird. When would you ever load demos into your data dir and additionally have a name collision

It's not just about the data directory. You could also have multiple other storage locations besides your usual config and data directories. For example you could have another storage location on a different drive that you use as an archive or backup for just some types of files (demos or maps).

> generally i think data dir should be considered read only anyway.

I agree. Furthermore, I think we have to consider all storage locations except the designated save location as read-only, because we don't really know which directory is the data directory after all storage paths have been added to `IStorage`. The first storage path is the save location, everything after that has no special meaning.

> My main worry is that this could confuse users who are used to the old way of merging the folders into one view.

This would mostly concern the editor, as most users don't use multiple storage locations for demos. Mainly this means that the standard maps are now found in a different folder instead of being shown in the combined view immediately. If users put their own maps in their data directory, they would also be more likely to realise that they should use config directory instead, when the maps are not combined into one view.

We could also add a dropdown menu or menubar to make the storage location selection more visible. Additionally we could show a small popup to onboard users when first opening the file dialog when multiple viable storage locations are found.

**Comment by Jupeyy** [comment]
The question is, if somebody especially wants this feature for e.g. the editor.

We could like in your video have a "combined" directory that combines all storages (as it is rn)
and if someone explicitly goes back in path `/..` then he sees the splitted ones..

Basically like drives in Windows (C:, D: etc.)
and the combines is simply select at default.. so without clicking `/..` u'd never notice the others

**Comment by Robyt3** [comment]
I guess using both is also an option, although I was sort of trying to avoid implementing the combined storage listing.

What if you have a file with name `foo.demo` in one storage location and a folder named `foo.demo` in another location? Should it be shown as a file or a folder, none at all, or whatever it is in the higher priority storage?

**Comment by Jupeyy** [comment]
guess higher prio, similar to how assets are loaded
