### ISSUE TITLE
Screen flickering weirdly since 16.2

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5559]
https://user-images.githubusercontent.com/2335377/177365521-06c76124-b6b6-4cc9-8a95-700b2cd2d2a2.mp4
Reported by LHP on Discord

https://user-images.githubusercontent.com/2335377/177365626-85265f8e-8d79-4945-b84a-f8dfc746eff5.mp4
As well as Dezarion on Discord with the same

**Comment by C0D3D3V** [comment]
Both on KoG server

**Comment by C0D3D3V** [comment]
Maybe related to this https://github.com/ddnet/ddnet/issues/5309 or the new input handeling.

But I can not reproduce the glitches on KoG server.

**Comment by sjrc6** [comment]
someone with the issue reported it stops happening with cl_predict 0 in kog discord, which might narrow it down slightly

**Comment by C0D3D3V** [comment]
Ah, I heard from one dev that KOG servers don't send a new character if you only move straight ahead, for example. This would explain why it is a problem on KOG servers to take the sent data to overwrite the predicted data.
So I guess it is the same problem as https://github.com/ddnet/ddnet/issues/5309

I will try to figure out a solution. (Actually I thought that is not a big problem, because the character data is used anyway to overwrite the prediction, but I probably missed something)
