### ISSUE TITLE
Period/comma hotkeys cause repeated action instances

### ISSUE THREAD

**Issue by VoxelDoesCode** [ddnet/ddnet#5779]
Relating to #5777, it seems that whenever I click comma\period whenever an event is happening (example: double jumping or someone joining), a duplicate is played. This can lead to a long string of repeated sounds, and a thread of copied messages.
![nCCKyai](https://user-images.githubusercontent.com/95713843/187054722-d98c390b-64cc-418d-b893-d423a16f1b39.png)
![unknown](https://user-images.githubusercontent.com/95713843/187054702-07d47ffe-b086-40d6-b3e8-38a066395b74.png)

This also seems to causes new sounds to go silent if you hold period. Say, you double jump. The jump sound is held in place of the current world and repeated each frame. New sounds don't emit such as hooking.

**Comment by C0D3D3V** [comment]
This sounds somehow expected, as @Robyt3 wrote here https://github.com/teeworlds/teeworlds/pull/2904#issuecomment-871669292

But the feature is also not so usefull in that way.

**Comment by Robyt3** [comment]
When you skip on upstream (except if you just skip on tick) it also resets the gameclient (calls `OnReset`) to remove old chat messages and effects. Adding the call is only one line but there are more changes needed here, as this change causes skipping to sometimes freeze the client (https://github.com/teeworlds/teeworlds/pull/2742). I chose to not call `OnReset` on upstream when skipping individual tick, so effects are still kept in that case. Otherwise explosions and smoke trails would immediately disappear when skipping ticks, which would look weird.

On upstream the following is additionally suppressed when skipping in demos:

- sounds
- stats
- info/kill messages
- anything caused by `COREEVENT_*` or `NETEVENTTYPE_*` in gameclient.

Chat messages are currently not suppressed while skipping, but they likely should be, as they spam the chat and console while skipping.
