### ISSUE TITLE
Overlay entities bug

### ISSUE THREAD

**Issue by BannZay** [ddnet/ddnet#580]
https://forum.ddnet.tw/viewtopic.php?f=45&t=3562
What about add possibility to hide things which not affect on gamepay on DDNet servers? Like ID 1&3 from front

This one may help d2179f67eddabe26d0a0674cdc08e5e912f29963

**Comment by timakro** [comment]
I introduced this behaviour when adding the feature to have clear entities for different gametypes, I explained my decision in the topic you linked: https://forum.ddnet.tw/viewtopic.php?f=45&t=3562&sid=1d7d253a1b1bfa2689e02758a12a72aa&start=10#p38900. Having unused tiles in your maps is bad anyways because they might be used in future versions. Though feel free to implement the removal of unused tiles when loading the map in the client again.

**Comment by BannZay** [comment]
@timakro , I understand, and I dont want to remove it, just to add possibility to hide it for players who use overlay entities for playing, not just testing

**Comment by fokkonaut** [comment]
close

**Comment by Learath2** [comment]
Working as intended
