### ISSUE TITLE
Let the game server provide a HTTPS URL for map download

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#5812]
This would be preferred over the built-in map download URL.

Need to figure out the security-related problems with this. This would allow an attacker to make the client make an arbitrary HTTPS GET request and check whether the response matches a given SHA256. A web browser can be made to make arbitrary HTTPS GET request, but can't check whether the response matches a given one. So the only difference is that the attacker can match the received data against expected data. How much worse is that? Probably a lot? @Learath2

**Comment by Learath2** [comment]
So the type of attack we'd be worried about is a GET request to some protected resource. If the server can predict what a successful request would look like it can first make sure the request went through and second maybe bruteforce out some details.

However, the client wont have any cookies so that rules out a huge set of targets for this sort of attack. Maybe some internal resources or ip whitelisted resources could be targetted but honestly this doesnt seem feasible either given in this case predicting what the result should look like would be even harder without a very targetted attack.

The only attack I can imagine extracting out information would be the bruteforce and honestly the search space is massive, the hundreds of repeated download attempts would be a dead giveaway. Maybe the client could just refuse to try again and directly download from the gameserver? In that case the bruteforce cant be automatic either

Can you think of any other attacks possible with this sort of arbitrary get + the hash of the reault of the get being returned?

**Comment by def-** [comment]
What I can imagine:
- Send the requests to a honeypot web server with some hacking-like url (wp-admin, ...) to get people into legal trouble
- Download a huge file, but players will see that the file size is 10 GB and takes a while
- Download a huge file that is extremely well compressed with gzip transparent compression, thus filling up player's disk space

**Comment by ElvisDot** [comment]
Not sure if it is a problem. But since the server gets a response it could check wether http services are up or not that are only reachable from the clients network. Or does enforcing https solve that issue? Stuff on localhost is usually not having ssl. Neither does the smart fridge that only has a ip. But maybe the external web server that can only be reached with the whitelisted ip of the client.
