### ISSUE TITLE
Speed change problem in demo viewer with mousewheeldown

### ISSUE THREAD

**Issue by PathosEthosLogos** [ddnet/ddnet#607]
(Is 1.5x implemented? I think the text needs to be fixed in the demo viewer, because it still shows 2x. So right now, I think it shows the text "2x" for both 1.5x speed and 2x speed.)

When speeding down with mousewheeldown, it speeds down twice.

**Comment by Henningstone** [comment]
I can confirm both stated problems.
- The first originates from rounding things that better not be rounded ([»code](https://github.com/ddnet/ddnet/blob/b42ae74d29d04e650ecc4651202d3cf0cd24456b/src/game/client/components/menus_demo.cpp#L376-L377))

- The second one is not a bug, it's a feature :smile: It's being decreased twice because it's simply being decreased twice, first [here](https://github.com/ddnet/ddnet/blob/b42ae74d29d04e650ecc4651202d3cf0cd24456b/src/game/client/components/menus_demo.cpp#L172-L176), then [here](https://github.com/ddnet/ddnet/blob/b42ae74d29d04e650ecc4651202d3cf0cd24456b/src/game/client/components/menus_demo.cpp#L363).
Funfact: the second one might look like some kind of leftover, but they were both introduced in the same commit! (ik it might be a leftover anway...)
