### ISSUE TITLE
Autocomplete for chat commands

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#614]
It would be great if chat commands could be autocompleted like the player name autocompletion.
Example: `All: /s` -tab-> `All: /save`
This could speed up typing commands.

**Comment by Ryozuki** [comment]
You would need to request the server the commands or made them predefined on the client?

**Comment by PathosEthosLogos** [comment]
This sounds exploitable if you spam the request to the server.

I think if the client can detect that it's a proper DDNet server, it can come with predefined autocompletes.

**Comment by timakro** [comment]
Best solution would probably be the client calling /cmdlist. This would probably work on other gametypes as well since /cmdlist became quite a standart. It would also be save and wouldn't require protocol changes.

**Comment by PathosEthosLogos** [comment]
That's a great idea. If I'm understanding correctly, you're saying that the client and type "cmdlist" or the client can do that automatically when it joins. Then the client saves that cmdlist. Is that right?

**Comment by Henningstone** [comment]
I would advice against parsing the server's output to the /cmdlist command for several reasons.

At first it may not be consistent over different gamemodes nor is it guaranteed to be present at all. It might not even be consistent on different servers with yet the same gametype, so making it dependent on the gametype will still have chance of failure.

Another reason is that on servers which don't make use of chat commands, automatically sending /cmdlist (on connect for example) is definitely going to result in spam and will only be annoying rather than useful. Since there is no possibility to guess whether the /cmdlist command is present on the current server, it would come down to try-and-error where error would be spamming the chat.

There are only two types of servers on which you can be sure that it'll work:
1. Those with vanilla gametype, as these must not be modified in any way according to the rules
2. Your own official DDRaceNetwork servers.

Other servers with the DDNet gametype on it may aswell be modified in a way that you couldn't be sure for the /cmdlist command (or rather chat commands in general) to be present.


Considering all these points, to me it seems more reasonable to turn away from a god-like approach which could work over different servers, but is not guaranteed to, and instead introduce a proper system that could work like the one used for rcon autocompletion. Servers which have it implemented may use it for compatible clients, but clients do not need to depend on the server having it implemented.

**Comment by necropotame** [comment]
Thanks Henningstone. As an example, InfClass display the list of commands in a MOTD box, which means that you can't access it if the leader board is displayed, but at least, the output is not going away because of chat spam.
In addition, parsing /cmdlist will not provide any information about parameters, which is very important.
