### ISSUE TITLE
High memory peak during map loading, goes down just after

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6159]
On Arctic Festivity during map loading I see RAM usage going up to 1.5 GB, then once it's loaded it stabilizes at 1.0 GB. We could look not to copy layers, or at least only keep one copied layer around, then deallocate the old one before allocating next.

**Comment by Jupeyy** [comment]
1. sounds sane
2. RAM usually can swap

i bet the problem is simply that this guy uses 4k assets, i dunno who started sharing those and sell them as a big thing

**Comment by def-** [comment]
I'll run a massif heap profile to find the cause of memory usage: https://valgrind.org/docs/manual/ms-manual.html

**Comment by Jupeyy** [comment]
it's not crashing CPU side, its crashing bcs he uses high res textures on a GPU that is not made for high res monitors

one 4k texture  (e.g. tile set) uses over 100MB vram. Since the UI isnt deallocating and the skins aren't lazy loaded, 4-5 of these textures can cause quite some pressure already

For some reason ppl think that using 4k skins and 4k assets just works without disadvantages.
Besides the high VRAM usage it can probably cause quite some lag if the textures have to be sampled bcs such huge textures don't lie in an optimal way on the GPU (except ofc u have a very modern GPU that is designed for this)

Normally games ship multiple versions of textures. high res, not so high res. But if they do these modifications manually they also have to accept the crash, bcs i prefer we don't start to force ppl using full hd compatible assets

**Comment by def-** [comment]
Can we show an error/warning when such a high res texture is loaded?

**Comment by Jupeyy** [comment]
If you want to deal with triggered ppl. For ppl that use 4k monitors it should be ok to use these textures keep that in mind.

The vulkan error handling suggest to remove high res stuff bcs it ran out of memory, but ofc only at the crash itself ^^

**Comment by Chairn** [comment]
I also have around 1.6GB when on Arctic Festivity with black screen on loading (when transferring data to GPU), but otherwise it works fine except a case with a window popup with a gear wheel icon that i can't remember...

**Comment by Jupeyy** [comment]
still not related to system memory usage.

If we want bigger maps we can also simply add system requirements for newer backends, gl 1.x doesnt buffer any map data.

without custom assets the vram usage is around 1gb. i doubt that there are vk compatible GPUs that have less than 2gb vram tho.

here are some other potential savings
we still load 102 skins all the time (shipped with client). considering that they are probably never used investing in lazy skin loading would be helpful

similar for country flags 250 files

GUI lists that load images should also deallocate them again (dynamically load while visible)

maybe for ppl that only use entities, or only use design, we could not load either ones vertex datas, only problem i see is switching between will cause a lag bcs it has to reupload map data during gameplay.

We could theoretically allow the vulkan backend to use smaller textures implcitly, e.g. disallow 4k skins by resizing them, tho that would probs trigger some ppl similar to a warning. Also it would not fix the potential lag caused by even uploading the 4k skin for resizing, lazy loading skins should already help enough hopefully

or we can just keep it as is and call it a day, i am currently not really motivated to do any of these but i can provide information if somebody wants to try anything of these out

**Comment by def-** [comment]
Thanks for going into details @Jupeyy . If someone wants to work on this, now we have some pointers.
