### ISSUE TITLE
Just Pseudo Fly gives error in server console

### ISSUE THREAD

**Issue by bencie** [ddnet/ddnet#6489]
After downloading Just Pseudo Fly from https://github.com/ddnet/ddnet-maps/blob/master/types/brutal/maps/Just%20Pseudo%20Fly.map and voting that map on a LAN server, you get this error in the server console:
> collision: something is VERY wrong with the Front layer please report this at https://github.com/ddnet/ddnet, you will need to post the map as well and any steps that u think may have led to this
I tested it on multiple PCs, with custom server configs and default ones, and it always resulted in this error, so it's likely a problem with the map, don't know what it is.

Edit: Permalink to the file: https://github.com/ddnet/ddnet-maps/blob/c929ef286be00783fb8450b453a58f367f73a0f2/types/brutal/maps/Just%20Pseudo%20Fly.map

**Comment by Robyt3** [comment]
This message is shown because the when the entities at (1, 475±1) on the front layer are handled, the positions (-1, 475±1) are also checked, which are out of bounds of the layer:

![screenshot](https://user-images.githubusercontent.com/23437060/229315782-e1c72ac7-318b-4058-903f-d5bf70839fb0.png)

I guess those entities should be removed from the map?

I can make a PR to improve that error message, so it show the invalid the position that was accessed.
