### ISSUE TITLE
Refactor packer error

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#6525]
@Robyt3 you might be interested :)

CPacker is using a ``int``  for errors [m_Error](https://github.com/ddnet/ddnet/blob/15620354b99755c76ffe9880fb54a6c109a5751f/src/engine/shared/packer.h#L18)

But that seems to be from the int as a bool old tw days. So this should either be made a bool. Or imo better use different values for different errors. And then change this signature to ``int`` 

```C++
bool Error() const { return m_Error; }
```

The packer can fail in multiple places. If it happens would be nice to know where.

I somehow managed to break [this test](https://github.com/ddnet/ddnet/blob/15620354b99755c76ffe9880fb54a6c109a5751f/src/test/teehistorian.cpp#L117) in my fork xd thats how I noticed that the test could fail nicer with a error code that can be looked up instead of just saying it failed.

**Comment by Robyt3** [comment]
I think you are usually expected to call `Error` immediately after calling a function that can set the error flag, so you know which invocation failed. As far as I can tell, the packer can only fail if there is not enough space available, so there's isn't much need for different error codes as well.

`m_Error` could be a `bool` instead of an `int` then.
