### ISSUE TITLE
Mouse in editor can get stuck in layer dragging state

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#6529]
Reported by ReyDeuce on Discord:

https://user-images.githubusercontent.com/23437060/233840853-0e2cf919-ce82-42d6-8116-651349c1e42b.mp4

>> How did you get into this state?

> i dont know, i was just mapping
> and somehow i got stuck like that

As a workaround you can press Ctrl+Shift+S to open the Save As dialog, save the map and restart the game.

@Marmare314 Do you want to take a look?

More information: https://discord.com/channels/252358080522747904/757720336274948198/1099726560086478888

**Comment by teini94** [comment]
happened to me too  ~1 week ago

**Comment by Marmare314** [comment]
The layer being dragged implies that `s_Operation == OP_LAYER_DRAG`. Not being able to click implies that the dragged button cannot be active. And if `!CheckActiveItem(s_pDraggedButton)` the variable `s_Operation` is set to `OP_NONE`. So somehow `s_pDraggedButton` must be active while the dragged button is not. Not sure why that happens.
I guess it could be fixed by returning wether the button is active from `DoButton_DraggableEx`.

**Comment by Robyt3** [comment]
Let's assume it's fixed by #6542 and reopen if it happens again.
