### ISSUE TITLE
Autocompletion of player names resolves to incorrect name

### ISSUE THREAD

**Issue by d3fault** [ddnet/ddnet#659]
2 players in server: Acadia and TheAdmiralPanda. Acadia has a lower clientId (if that matters). When typing "ad" and pressing tab, Acadia is auto-completed whereas it should obviously be TheAdmiralPanda.

**Comment by def-** [comment]
Why should it obviously be TheAdmiralPanda? Acadia also contains "ad".

**Comment by d3fault** [comment]
man I'm stupid, kept staring at the Ac part only

**Comment by itsrachelfish** [comment]
@d3fault @def- despite this issue being closed, I'd have to say the current name resolution behavior is a little wonky. I was just playing a game with a few other players: Wonka, snailx3, and noby. When I typed "n" and then tab, the first result was Wonka, then snailx3, then finally noby. I'm guessing this order is based on the client id?

Wouldn't it make more sense to sort the autocompletion based on how close the matched string was to the beginning of a potential user's name?

**Comment by timakro** [comment]
I agree with @itsrachelfish, most autocompletion systems even only match names which start with the completed term.

**Comment by itsrachelfish** [comment]
@timakro I do like that teeworlds matches within names, but the order really should be based on "normal" auto-completion systems. One benefit of matching within names is that you can still highlight users even when they have silly gamer names like: **<<|| Pro Tee ||>>**

**Comment by Learath2** [comment]
The thing is commit e1ef01f is supposed to do exactly this. The implementation looks convoluted and I couldn't bring myself to decipher it.

**Comment by d3fault** [comment]
so I think the current implementation is _almost_ good, it just needs to be sorted once more at the end. the final sort should be by "index of the phrase being auto-completed", so that "n" auto-completes to "noby" even if "wonka" has a lower client ID or whatever. I tried deciphering e1ef01f as well but gave up pretty quickly

**Comment by Learath2** [comment]
If no one can decipher it I'd rather rewrite that completely tbh and bolting on another sort hardly sounds like a proper solution anyways.

**Comment by def-** [comment]
This seems to work totally fine to me.

**Comment by itsrachelfish** [comment]
@def- you really think if you type ```n``` -> ```tab```  "Wonka" should appear before "noby"? Generally autocompletion is based on the *beginning* of a string, not an unknown arbitrary client ID.

**Comment by def-** [comment]
Just tried it with players Wonka and noby, correctly autocompletes to noby for me.

**Comment by d3fault** [comment]
@def- i think the client id factors in, so connect Wonka and noby in
the opposite order. again, the fix is trivial: one more sort at the
end, by index-of the matching chars ('n' is index 0 in "noby", so it
should get sorted before 'n' with index 2 in " wonka")

**Comment by def-** [comment]
Tried it by switching the names too, still autocorrects correctly.

**Comment by d3fault** [comment]
maybe it's not deterministic then? ive definitely seen it behave the
way rachelfish described. did you try with every permutation of every
arch, os, os version, race, gender, and sexual orientation? i dont
have the technology to run tw atm (rip life) so i cant test :(

**Comment by hugo-dlb** [comment]
This issue still appears for me.
It does not autocomplete based on the first string matched.
It's pretty annoying when you want to reply fast to someone.

**Comment by def-** [comment]
@hugo-dlb any way to reproduce?

**Comment by hugo-dlb** [comment]
Here's a GIF showcasing the issue :
![tw](https://user-images.githubusercontent.com/3577405/71322154-cd03f500-24c4-11ea-8a37-ee2873093767.gif)

There are 4 players : 
- abcdef
- aabcdef
- aaabcdef
- aaaabcdef

If I type ab and push tab, abcdef comes up, as it should.
If I type bc and push tab, aaaabcdef comes up, where as abcdef should come up.

**Comment by def-** [comment]
>  If I type bc and push tab, aaaabcdef comes up, where as abcdef should come up.

I don't understand what's wrong with this, it works as intended. What we do is:

1. Try to find names starting with `bc` and return them in sorted order
2. Try to find names containing `bc` and return them in sorted order

What do you propose to return instead? The name where bc is in the earliest location?

**Comment by hugo-dlb** [comment]
As a French person I'm reading left to right, so I would expect that abcdef would come up first since bc is in the earliest location.

Here's another example:
![tw2](https://user-images.githubusercontent.com/3577405/71322565-2f5ef480-24c9-11ea-9be2-3790dd36caf3.gif)

In this situation say I want to tag Dp'Chup Chup'. Dp are special characters and ' is uncommon so I might think that by typing ' and pressing tab, Chup Chup should come up, but #1 Nerd' comes up first whereas ' is at the end.
This is really a UX improvement, but you think that it doesn't make sense, maybe it doesn't need a change.

**Comment by Learath2** [comment]
Assuming people usually use something close to the beginning of a name rather than considering lexicographical order, it actually doesn't sound that bad to find the earliest location where substring appears.

**Comment by d3fault** [comment]
Issue still appears for me too, but it's difficult to reproduce.
Sometimes I get the result I want, sometimes not. Appears to be
random/indeterminate.

**Comment by itsrachelfish** [comment]
@hugo-dlb @d3fault As I explained in 2017, this issue is being caused because autocompletion is based on the order that users have connected to the server (their client ID). This is why the behavior is inconsistent and appears to sometimes work but sometimes not.

Originally I assumed this based on the behavior I saw in game, but since this is still an open issue I decided to look at the source code to test my hypothesis. https://github.com/ddnet/ddnet/blob/e02cd322ade5f479dd21685a43209d70ace344c1/src/game/client/components/chat.cpp#L388-L426

You can see here that autocompletion is performed using a for loop over all possible client IDs. As soon as a match is found, the loop breaks.

**Comment by Learath2** [comment]
The index there is used to index into an array of client pointers sorted by
name. So that shouldn't be an issue
