### ISSUE TITLE
ON button causes micro stutters to other solo-server players inside switch-freeze

### ISSUE THREAD

**Issue by Destoros** [ddnet/ddnet#6644]
The title basically explains it. Players on a solo server can affect the visuals of others by constantly standing on an ON button, if that ON button causes switch-freeze to be turned on.

Video explanation : First i move through a turned off switch-freeze on a solo server which works as expected - no micro stutters during movement and hook is visible. Next I toggle to my dummy, place him on the ON button and start moving on my main. Now there are micro stutters and hook is not visible.

https://github.com/ddnet/ddnet/assets/59802456/406f9c9a-7706-4545-8df5-3969e279d03c

Unfortunately, the video doesnt show these micro stutters well, they are way worse when actually playing.

The next video shows that this bug only occurs, when the other tee (i.e. my dummy) is rendered using /showothers.

https://github.com/ddnet/ddnet/assets/59802456/ef321f9e-79c6-40c8-ad41-ccb9b12dc6c9

Map to test this bug:
[map_solo_server_switch_bug.zip](https://github.com/ddnet/ddnet/files/11525513/map_solo_server_switch_bug.zip)

**Comment by Robyt3** [comment]
Looks like a prediction bug for switched freeze tiles. I couldn't really notice any stutters, but I can confirm that the hook flickers when used from inside the switched freeze tiles with `cl_predict 1`.

**Comment by trml** [comment]
I think there are perhaps causes of this problem. One is that the server internally places players on solo servers on different teams (and that switch state are snapped/send with these internal team numbers, not team 0), while the client is told that it is in team 0. Another is that there might be some prediction of the dummy, which will cause problems if the dummy gets predicted to trigger a switch in team 0 (I'm not sure if this prediction of dummy in solo parts is still present).

A purely client-side solution could be to remove all prediction of other players while in solo (including dummy) if this is not already done, and to also remove team information from the prediction as far as possible. (And for example use the team returned by CGameClient::SwitchStateTeam() to predict switch state rather than the individual players team)
