### ISSUE TITLE
Chat bar ban

### ISSUE THREAD

**Issue by XCWQW1** [ddnet/ddnet#6963]
If the player frequently hits a space in the chat bar and sends it out after a while, he will be banned
---
如果玩家在聊天栏频繁的打一个空格发送出去过一会会被禁言

**Comment by murpii** [comment]
> ## If the player frequently hits a space in the chat bar and sends it out after a while, he will be banned
> 如果玩家在聊天栏频繁的打一个空格发送出去过一会会被禁言

Could you record a video showcasing the issue you're describing?

**Comment by XCWQW1** [comment]
[2023-08-04 11-07-52.zip](https://github.com/ddnet/ddnet/files/12256672/2023-08-04.11-07-52.zip)

**Comment by Robyt3** [comment]
The client sends empty chat messages to the server and the server also sends the empty chat messages back to the client.

But the client doesn't show empty text messages in chat and console. Therefore you don't notice that you are triggering the spamprotection.

We should change client and server so empty chat messages are not being send at all, since the client never displays them anyway.
