### ISSUE TITLE
Demo Player: Add a config option to define the duration of the skip/rewind feature

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#7064]
Title. 10 seconds is sometimes simply too much. Having a option to alter the duration would be nice.

**Comment by Robyt3** [comment]
I don't like adding an option for this. By the way, using left/right arrows skip 5 seconds whereas using J/L skip 10 seconds.

Skipping to markers doesn't currently have any hotkeys. I would suggest Ctrl+Left/Right for this, since it's like this on upstream already.

Upstream also allows holding Shift to skip 30 seconds instead of 5 seconds. Either we adopt exactly the opposite, making Shift change the skipping time to 1 second instead, or we adopt upstream exactly and also Alt+Shift/Right to skip only 1 second.

**Comment by Robyt3** [comment]
If you truely need variable skipping duration, we could scale the skipping duration by the playback speed. This is actually what YouTube does, although I'm not sure if it's actually a good idea.

**Comment by murpii** [comment]
> I don't like adding an option for this. By the way, using left/right arrows skip 5 seconds whereas using J/L skip 10 seconds.

> Upstream also allows holding Shift to skip 30 seconds instead of 5 seconds.

That would be 3 [undocumented] ways of skipping/rewinding. This does not contribute to a positive user experience at all imo.

**Comment by murpii** [comment]
I'd suggest replacing the 'Go forward one tick' and 'Go back one tick' with something adjustable and have one universal keybind instead.
