### ISSUE TITLE
Some tooltips don't work anymore.

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7107]
I found that the following tool tips don't seem to work anymore, 
- "Your movements are not taken into account when calculating the line colors" on the hook collisions page.
- "Toggle to edit your dummy settings" on the player page.

**Comment by Robyt3** [comment]
- "Choose default eyes when joining a server" on Tee settings page when hovering eyes.
- maybe more

Anything where there is no button logic associated with the ID used for the tooltip, since #6685 (bbe2430be90029caad38734cab62ce077f7ee6c2) requires this to ensure that tooltips are not rendered when the associated UI element is covered by another UI element.
