### ISSUE TITLE
#7016 breaks zooming.

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7113]
Their change (#7016) sets the zoom back to default every tick while you aren't in spectator meaning you wouldn't be able to change the zoom while playing.

**Comment by def-** [comment]
@k-i-o Can you fix this?

**Comment by k-i-o** [comment]
> @k-i-o Can you fix this?

I have some work to do today, I'll take a look tomorrow

**Comment by Vy0x2** [comment]
[Issue 7010](https://github.com/ddnet/ddnet/issues/7010) requested: When leaving the spectator mode, the zoom should be default again.
But why? This behaviour doesnt appear in free view too. If you zoom out in free view and go out of the spec mode, you still keep the zoom.
Why should this change with multi view?

To implement this behaviour, you would have to implement a logic that tracks when you leave spec mode and check if you left out of freeview, follow mode or multiview.
That would add unnecessary complexity imo.
Thats why i suggest to remove that behaviour introduced in [Pull request 7016](https://github.com/ddnet/ddnet/pull/7016).

I already created a pull request in order to do that [Pull request 7125](https://github.com/ddnet/ddnet/pull/7125), since i dont have time to fix that during the week.

**Comment by Robyt3** [comment]
Closed by #7125.

**Comment by k-i-o** [comment]
> [Issue 7010](https://github.com/ddnet/ddnet/issues/7010) requested: When leaving the spectator mode, the zoom should be default again. But why? This behaviour doesnt appear in free view too. If you zoom out in free view and go out of the spec mode, you still keep the zoom. Why should this change with multi view?
> 
> To implement this behaviour, you would have to implement a logic that tracks when you leave spec mode and check if you left out of freeview, follow mode or multiview. That would add unnecessary complexity imo. Thats why i suggest to remove that behaviour introduced in [Pull request 7016](https://github.com/ddnet/ddnet/pull/7016).
> 
> I already created a pull request in order to do that [Pull request 7125](https://github.com/ddnet/ddnet/pull/7125), since i dont have time to fix that during the week.

i think that are different things, in free view you can choose the zoom, in multiview thats automatic su you don't want the zoom that the game set
