### ISSUE TITLE
Long log messages are cut off in console

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7132]
![image](https://github.com/ddnet/ddnet/assets/141338449/bd62ac9e-438f-41e4-9ece-434b57a17594)

**Comment by Robyt3** [comment]
Seems intentional:

https://github.com/ddnet/ddnet/blob/228d9967cbc7f30c3845d86144af96b6bb3f8ef3/src/game/client/components/console.cpp#L368-L371

But it has been like this [since at least 13 years](https://github.com/ddnet/ddnet/blame/228d9967cbc7f30c3845d86144af96b6bb3f8ef3/src/game/client/components/console.cpp#L371) so maybe we can change it.
