### ISSUE TITLE
DDNetLaser type FREEZE and DOOR won't take custom startTick anymore?

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#7155]
When they got added it was possible to adjust for example the thickness by modifying the starttick.
It seems like that only works for regular lasers (rifle) and shotgun now.
That's really sad for mods, and I really wonder why this was required for ANTIPING OFF.

I suspect this commit: https://github.com/ddnet/ddnet/commit/e10f52821510fe37b47aa91de627b7bba2235b27
@trml could you change that again and adjust it to work the way it worked before? It broke something in my mod, and as I said I don't see a reason to do that clientside without antiping. Or could there be a workaround to achieve the same results?

**Comment by heinrich5991** [comment]
> adjust for example the thickness by modifying the starttick.

That's a hack, I think it even changes how well it works depending on the ping of the player. I don't think we should try to modify the code to support it (again).

**Comment by fokkonaut** [comment]
> > adjust for example the thickness by modifying the starttick.
> 
> That's a hack, I think it even changes how well it works depending on the ping of the player. I don't think we should try to modify the code to support it (again).

Couldn't we make startTick -1 indicate the client should determine it by itself, while all other start ticks would be acceptable by the server? See no downside in this and it would make these lasers (for color variation) act the same way as rifle and shotgun lasers.

**Comment by trml** [comment]
To the original question: It seemed strange to me that a lot of network optimization went into vanilla to make sure characters that are standing still are not sent in the delta snapshot every tick (and some work in ddnetcharacter as well), while laser doors gets sent in the delta of every snapshot just because the starttick has to get updated with the current tick (to ensure that the laser stays visible). So it was mainly a network optimization.
And it also makes it unaffected by lag or snap rate, as pointed out.

> Couldn't we make startTick -1 indicate the client should determine it by itself

I considered this, but then it couldn't be changed again without breaking compatibility for clients, and I also wasn't sure if its the best solution.

Does it actually make sense to use a tick to communicate the thickness of a laser door in the first place? Wouldn't it for example be better to just send a static value, like 0 for regular size, 1,2,3,4 for larger, -1,... for smaller, or something similar?

**Comment by fokkonaut** [comment]
Oh, and I just noticed: I use this feature already, and i actually don't think its a bug, since freeze doors use the same behaviour to be smaller than actual doors.

Also, in my case currently it's lucky because I decided to use the shotgun colored laser for the specific kind of "wall" that's placeable. I also have a taser, which shoots freeze type of lasers, as it freezes the laser.
It's inconsistent and really mod-unfriendly.

I remember back then, a change was proposed that would have included removing hammer projectiles (the white dots). I was heavily against that, as it was used in many mods already, including mine, and it's just something teeworlds offers to use for mods.
I think it's very sad if we will be unable to use the colored laser types equally.
Especially since it was a thing already and just flows with the consistency. I have no problem with clientisde starttick calculation for antiping ON. That's a whole different story.

**Comment by trml** [comment]
Again, I didn't implement this in DDNetLaser pr because I wanted some discussion about how to send custom laser width first. Is there a reason to not just send the width directly rather than calculating it from a the gametick? The one reason I can think of is if you to still easily have the flickering/pulsating effect.

Also, this is unrelated to antiping, since lasers are not affected by antiping (except lasers fired by your own character).

**Comment by fokkonaut** [comment]
> Again, I didn't implement this in DDNetLaser pr because I wanted some discussion about how to send custom laser width first. Is there a reason to not just send the width directly rather than calculating it from the gametick? The one reason I can think of is if you to still easily have the flickering/pulsating effect.
> 
> Also, this is unrelated to antiping, since lasers are not affected by antiping (except lasers fired by your own character).

Do it as you wish. I think using the startTick makes most sense, as that's also the vanilla way to go and that's basically how it's used on the client sife aswell.
We shouldnt overcomplicate things I guess

**Comment by fokkonaut** [comment]
Also @trml if this is something we have to discuss it would be very kind if we agree on something before a breaking change.
That's how @heinrich5991 usually wants to have that done. Right now 17.3 would get released without it, means much more backward compatibility code on my side, which heinrich usually also wants to keep as less as possible. (And so do I)

**Comment by trml** [comment]
@fokkonaut I'm fine with this solution, just wanted to consider other possibilities as well, but after looking at it will perhaps be most consistent to use starttick here, since that's what used for laser and shotgun.

(I don't think any of these changes would be breaking though. Since the old clients ignore starttick you can more or less choose any solution and still be compatible, except that servers now send 0 instead of -1 if you want to change that)
