### ISSUE TITLE
vec2 in src/base/vmath.h could be refactored into simply a subclass of std::complex

### ISSUE THREAD

**Issue by u8y7541** [ddnet/ddnet#717]
I was reading through the source code and I realized that instead of reimplementing a 2d vector, it could have just subclassed std::complex; std::complex provides all of the base operations and if anything else is needed it can be easily added in.

If there is any specific reason why this wasn't done, I'd like to know.

**Comment by Learath2** [comment]
Teeworlds (ab)uses C++ as C with classes. You can see the C++ standard library is not used anywhere outside code added in dd(net/race).

It can't/won't/shouldn't be reworked as `std::complex` because it could introduce different physics invalidating ranks, besides we don't touch `base/` unless it is to fix a bug or to add a new feature, both of which are done using only C features. If it ain't broke don't fix it :)

**Comment by u8y7541** [comment]
Yeah. I tried to implement a vector2_base class by subclassing complex and by the way it went it looked like it was going to be bigger than teeworld's re-implementation; not to mention that complex multiplication and division is vector multiplication and division. There's a lot of code involved that really doesn't do anything and it ends up that re-implementing it is _actually simpler._
