### ISSUE TITLE
Add Blockworlds server(s) in community tab

### ISSUE THREAD

**Issue by NouaaTW** [ddnet/ddnet#7448]
right now, Blockworlds servers are still tagged as "kog." It would be great to create our own category.

I took a peek at the code, and honestly, it's not super intuitive to me. I'll give it another shot as soon as I have time.

I'm throwing our logo in there, just in case someone wants to get their hands dirty! 😎

![blockworlds](https://github.com/ddnet/ddnet/assets/75568768/0c3aac99-8c7a-4021-a65c-324eb060e58c)

**Comment by heinrich5991** [comment]
I don't think you need any code changes. Just a list of server IP addresses and a logo that fits in that place and fits the other logo's styles.

**Comment by Robyt3** [comment]
The community information and icons come from https://info.ddnet.org/info and the URL specified in there. You can try your own communities and icons locally by adding the information in your local `ddnet-info.json` and adding the icon file to the `communityicons` folder in your config directory. For testing, you have to mark the `ddnet-info.json` file as read-only so it's not automatically overridden by the downloaded info. Information about the new json entries can be found in https://github.com/ddnet/ddnet/issues/5654#issuecomment-1742090494.

The community icons should be 128x64 pixel RGBA PNG images. They should be compatible with pnglite due to the warning popup being shown otherwise. Please first test the icon locally to ensure that it looks good at the resolution displayed in the client and that it fits together with the other images.

**Comment by NouaaTW** [comment]
all right, thanks. What should I put in the flagID field? @Robyt3

**Comment by Robyt3** [comment]
> What should I put in the flagID field?

Use the numeric values from [`data/countryflags/index.txt`](https://github.com/ddnet/ddnet/blob/a329417dee5002bf4c31ef6b5e0fde5d4920e0d8/data/countryflags/index.txt).

We currently use the EU flag for all European DDNet servers, where KoG uses individual country flags for their European servers (e.g. German flag for German servers), you can choose to adopt either way.

**Comment by archimede67** [comment]
It seems like Blockworlds has been added to the communities
![image](https://github.com/ddnet/ddnet/assets/13364635/2416fac9-c0a8-4834-b9df-dd810c8d07ed)

I guess we can close this?

**Comment by NouaaTW** [comment]
yep
