### ISSUE TITLE
TODO: remove this

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#7472]
13 years ago magnus decided to remove this include. What was his plan? Maybe merge both files into one?

https://github.com/ddnet/ddnet/blob/55098cd3132c94f65f02a4fc2081dbfd27f9e1aa/src/engine/shared/config_variables.h#L6-L7

I guess it is time to tackle this todo comment. My proposal would be to simply delete the todo comment (won't fix). Another alternative would be to merge both files into one. I personally use variables.h for client stuff and config_variables.h for server stuff and enjoy the separation.

**Comment by Robyt3** [comment]
I don't like how there are two files, because it's often unclear which file the variable you are looking for is declared in or which file you should declare a new variable in, so I'm leaning towards merging the files (I'd say the file should stay in engine, so we don't include a `game` file from `engine` anymore).

**Comment by ChillerDragon** [comment]
> I don't like how there are two files, because it's often unclear which file the variable you are looking for is declared in or which file you should declare a new variable in, so I'm leaning towards merging the files (I'd say the file should stay in engine, so we don't include a `game` file from `engine` anymore).

Oh yea I know that pain. That is a good point. I am also for merging game into engine because not all configs are game related. Such as logger level output or port.

So remove variables.h? Anyone has any objections to that?
