### ISSUE TITLE
allow the console log to recognize and handle URLs.

### ISSUE THREAD

**Issue by BlaiZephyr** [ddnet/ddnet#7851]
i always thought about it more as a meme, but at some points i would personally find that useful, its just a small QoL as you can just copy paste, but i'd find it useful in some scenarios - espacially because i share a lot of links in interactive Discord (ddnet)

**Comment by Robyt3** [comment]
The problem with this is the same as the benefit: you can now open arbitrary URLs with the click of a button.

https://github.com/ddnet/ddnet/blob/ddd3d2506627c31b82441d7fd9f642110e1fddf5/src/base/system.h#L2082-L2084

This would need very extensive validation to ensure the link is actually a valid URL so it doesn't result in outside arbitrary code execution. Even then I'm not sure it's a good idea to make it easier for players to click links to malware which are spammed in the chat.

**Comment by archimede67** [comment]
We could probably do something similar to discord where we show a warning popup for an untrusted domain. The players can also decide if they want to trust all links from that domain or not, so that way it is more likely that they will make sure the link is safe, while avoiding to confirm each time if you share a lot of links from the same domain (github.com for example).

**Comment by Robyt3** [comment]
Seems like a lot of effort for a minor upgrade to convenience. As a power user you could copy the link in the console with Ctrl+C, press Win+R, Ctrl+V, Enter and achieve the same thing (on Windows).

**Comment by heinrich5991** [comment]
I'd prefer to keep the usability on opening arbitrary links down. Agreeing with @Robyt3 here.

**Comment by BlaiZephyr** [comment]
alright then! thanks for giving feedback!
