### ISSUE TITLE
Forbid escaping base directory 

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#787]
@def- I don't know what 1b0de108c63e4652555a35cf20a06d1ecab1d966, 624fd381888b25d73d5acd96137fb4a7a251bb66 and d3daa51486f4629e38ca69a2cf79301d213dda05 do but they break my configfile system.

**Comment by def-** [comment]
For trashmap you mean? See https://github.com/ddnet/ddnet-trashmap/commits/master

**Comment by timakro** [comment]
No trashmap works fine, I don't know what you did there again ^^. The Unique clan servers don't work, the setup I'm using there is not on github though.

**Comment by def-** [comment]
You can only access files from base directories, no more absolute paths and ..

This is necessary as a security measure, since you can use change_map to get other people's maps, or exec to read other config files and find out passwords.

There are a few ways to fix this now:

1. Copy the necessary files into the directory (what I did with trashmap)
2. Make a symlink to the directory you need access to (used for DDNet Nuclear Test servers)
3. Add another path in storage.cfg (used for all DDNet Test servers)

**Comment by timakro** [comment]
Thanks, the storage.cfg tip helped!
