### ISSUE TITLE
sv_shutdown_when_empty stops the server on map change

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#791]

**Comment by def-** [comment]
Makes sense, because the server is empty when you change map!

**Comment by timakro** [comment]
The option is intended to apply new changes when nobody is using the server anymore. Currently this ensures that no races are interrupted. But the server is still used and it is strange when you vote another map and you except your client to reconnect but it timeouts on the "connecting to server ..." screen.

**Comment by savander** [comment]
but it should be that way. It's better to restart server on map change, than when people are on race

**Comment by timakro** [comment]
@savander What I'm saying is that it would be even better to start it neither on mapchange nor when people are racing.

**Comment by def-** [comment]
You could argue either way.

Switching the server to new version can be good since we sometimes fix severe bugs that could crash the server etc.

On the other hand it's a slight inconvenience for the players, having to switch the map again after the server restarted.

I'm not sure which is better to have.

**Comment by savander** [comment]
I would stay with that slight inconvenience. :)

**Comment by timakro** [comment]
Okay

**Comment by def-** [comment]
Instead we should fix that it shows a timeout in the client. Not sure how though.
