### ISSUE TITLE
Collect data about time you've spent on a certain map regardless of finish.

### ISSUE THREAD

**Issue by lukitsche** [ddnet/ddnet#7944]
Example SQL Table:
```
Map    Name    Time    Timestamp
Stronghold    cauldron    2203.8    2022-11-19 22:17:01
```
Actually like the *race* table in the ddnet.sqlite dump. Columns explained:
* Map: Name of the map.
* Name: Name of the player.
* Time: Time spent on the server until disconnect.
* Timestamp: Timestamp of **disconnect** from server.

Assuming you always reconnect to the server when the map changes.

With this data you could see how much time you've spent on a certain map in total.
You could calculate different statistics about your playing behavior or success rate.

Either save the data locally on the clients pc, or have a public database online.

**Comment by furo321** [comment]
I don't think this information should be collected by the server, but should be done externally instead. You may be interested in https://ddnet.org/stats/master/, which contains master server data (list of all servers along with the clients connected to them) since 2021-05-18.

> With this data you could see how much time you've spent on a certain map in total.

You can checkout <https://ddstats.qwik.space/player/cauldron/activity>, which shows this along with other data related to playtime.

**Comment by ChillerDragon** [comment]
Ye like furo said. Seems out of scope for ddnet. It would pollute the official database which is big enough already. You either can do it in your custom ddnet modification. Or rely on the existing projects out there.
