### ISSUE TITLE
`Indicate map finish` disappears after disabling it and refreshing.

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#7957]
Most likely due to the fact that `info.ddnet.org/info` won't be contacted after disabling it.

https://github.com/ddnet/ddnet/assets/141338449/2d4c182b-cc79-45d9-bdc1-29607b14b912

**Comment by Robyt3** [comment]
@heinrich5991 This seems to be caused by #7459. The ddnet info json does not include a `finishes` array when no `name` GET parmeter is specified (i.e. when "indicate map finish" is not checked). After #7459 client assumes that no finishes are available, when `finishes` is not an array. Either we include an empty `finishes` array for DDNet (and other communities in the future if we support showing finishes for them), or we need to specify separately (e.g. as a `bool`) whether finishes are available for each community, or we hard-code the case for DDNet in the client and send empty arrays only for other communities if they support finishes.

**Comment by heinrich5991** [comment]
Hmmmm. What's the best way to indicate that a community supports sending finishes? Probably a bool or so?

Maybe we should hardcode it for DDNet servers only since the current system isn't likely going to work for third-party hosters anyway because they don't host their DB on ddnet.org?

**Comment by Robyt3** [comment]
I think always sending an empty `finishes` array for DDNet would be the most pragmatic solution now. It wouldn't require adding more special cases in the client so it would also retroactively fix the issue for 18.0.3.

**Comment by heinrich5991** [comment]
> I think always sending an empty `finishes` array for DDNet would be the most pragmatic solution now. It wouldn't require adding more special cases in the client so it would also retroactively fix the issue for 18.0.3.

It seems weird to return an empty array though. Perhaps it could be `null` instead?

**Comment by Robyt3** [comment]
> It seems weird to return an empty array though. Perhaps it could be `null` instead?

If we send `null` then old clients will discard the community entry because they expect the `finishes` attribute to be either an array or missing.

I'll add a separate attribute `has_finishes`.
