### ISSUE TITLE
bad binding

### ISSUE THREAD

**Issue by sojalei** [ddnet/ddnet#796]
bind - `bind c say q`
when I press keyCode(174) works this bind

**Comment by def-** [comment]
You can find out what your client thinks a key is called by setting it in the gui settings.

**Comment by sojalei** [comment]
omg, minus volume it's c and plus volume it's b

**Comment by Socialdarwinist** [comment]
The whole binding system has to be replaced for it to cease to interpret input as characters. The current system always missbehaves, at least on X11-based systems. For example as the French keyboard layout has ­­⟨é­⟩ on 〈AE02〉, the default binding for the gun does not work. Instead, as I have heard, you bind to “F14” for that key. Or that the team chat is on 〈AD06〉 instead of on 〈AB01〉 on German layouts. For Russians the keyboard does virtually not work at all, insofar as they lack the Latin characters in their layout, see AllTheHaxx/AllTheHaxx#287. Other layouts lack numbers in the upper row completely. One cannot bind either onto the non-Latin characters on these locations, which would not be a solution anyhow, as one can have a varying number of keyboard layouts. One should not be forced to switch to the English keyboard layout. DDNet currently practises polyglot shaming.

Look at the [binds.cpp](https://github.com/ddnet/ddnet/blob/a4752e7dd41c036d1b1dacf63ebc2f0a9de4c87e/src/game/client/components/binds.cpp#L116), see the difference between the entries:
```
	Bind(KEY_F1, "toggle_local_console");
	Bind(KEY_F2, "toggle_remote_console");
	Bind(KEY_TAB, "+scoreboard");
	Bind(KEY_BACKQUOTE, "+statboard");
	Bind(KEY_F10, "screenshot");

	Bind('a', "+left");
	Bind('d', "+right");
```
This has to be quitted. The A key, typically 〈AC01〉 on keyboards, should be referred to as KEY_A instead of being dealt with as string or whatever it takes to ensure that that position is used for the movement bindings, which is fixed to be compatible accross the world in this century and beyond, see the foundations in [SDL_scancode.h](https://github.com/ddnet/ddnet/blob/98a2f459b6bf0a1df55a081e750e3678844b524b/scripts/SDL_scancode.h). If I type in “bind a”, it should be 〈AC01〉 and not the respective key on the keyboard layout. Intuitivity is no argument when the intuitive approach is broken, and as for users using the console some more intricate approach can be expected.

For the sake of clarity, the current syntax of the .cfg can be exchanged for a more explicit one, like` bind key SCANCODE_Y "+showchat"` requiring converting old-style config files in newer versions of the client. Anyhow only advanced users bind via the console. The binding system can be replaced without common users noticing it.
