### ISSUE TITLE
segafult when create a bezier curve and right click on it

### ISSUE THREAD

**Issue by MilkeeyCat** [ddnet/ddnet#8020]
1. Go to editor
2. Open envelope tab
3. Click on "Color +"
4. Set curve to bezier
5. Rick click on point

**Comment by Robyt3** [comment]
Seems to happen only if you follow the steps exactly. If you add another point, or select another point first then it doesn't seem to crash anymore. Could be related to #8017.

**Comment by MilkeeyCat** [comment]
at first i wanted to try to fix that issue but i ended up fighting with this one :\

**Comment by MilkeeyCat** [comment]
Hey, Ive spent some time in da code and I think I know why it happens, I tried to solve it but I dont know how good the solution is https://github.com/ddnet/ddnet/compare/master...MilkeeyCat:ddnet:fix_bezier_control_point_popup So what was happening is you were clicking on the bezier out tangent and `m_SelectedTangentOutPoint` didnt have any elements and it(and none was pushed yet) so it was crashing when it was trying to read first element with `.front()` in `PopupEnvPoint`.

**Comment by Robyt3** [comment]
@MilkeeyCat Your analysis seems correct but the whole block of code that shows the color selector for color envelopes should not be active when a bezier control point is selected. It currently changes the color of the previously selected envelope point unrelated to the selected bezier control point because of this. Instead, the condition `pEnvelope->GetChannels() == 4` in `CEditor::PopupEnvPoint` and in [`ShowPopupEnvPoint`](https://github.com/ddnet/ddnet/blob/758664c29d0ce486a23c6cbb4e51c609354a1fd0/src/game/editor/editor.cpp#L6751) should be adjusted.
