### ISSUE TITLE
Remove me.

### ISSUE THREAD

**Issue by VoxelDoesCode** [ddnet/ddnet#8127]
I'm tired of this game, and I'm tired of having to be tied within development with this game. The community sucks, the developers are complete snobs, and no good update has been released for 5 years straight. I request that all the features that I added in will be removed.
That's right, the sitting, the laser colors, even the useless ones no one uses. All gone. I'm done. Nobody likes them anyways.

After everything is removed I will be installing a different client and permanently banning myself from every server so that I don't have to touch this god forsaken app again.

**Comment by ChillerDragon** [comment]
As a quick test I checked what this would do

```
git log --author=VoxelDoesCode --pretty=format:"%H" | xargs git revert
```

And it throws a bunch of conflicts. Not all of them are easy to solve. What about the code that was built on top of your features @VoxelDoesCode are you saying that the contributions of others should also be reverted? Or can we keep the features that were already updated by others? Or what process do you suggest here.

@Learath2 mentioned on discord that the license conflicts with this request. I am not sure what that means in detail but even if that was true I do not think that referring to the license is a nice way of handling such requests.

Maybe there is an easier way of solving the issue here. I do not fully understand the issue with your contributions staying @VoxelDoesCode so only you can tell if there is another way of solving the problem. Do you see any alternative that would also work for you?

**Comment by RIH-Cellegen** [comment]
I think this should be a violation of many principles regarding copyright safety on said repository, at least there should be a repository protection act on Github's ToS, there should be one.
Imma look into it and see if there is anything which contradicts the request. (This ain't normal to contribute this much, then request all of it's deletion, whenever other contributers just built their own stuff based off of your contributions. Not okay at all.)

**Comment by RIH-Cellegen** [comment]
> I think this should be a violation of many principles regarding copyright safety on said repository, at least there should be a repository protection act on Github's ToS, there should be one. Imma look into it and see if there is anything which contradicts the request. (This ain't normal to contribute this much, then request all of it's deletion, whenever other contributers just built their own stuff based off of your contributions. Not okay at all.)

So, about removing your contribution, in Github's terms, it is called [Content Removal Request](https://docs.github.com/en/site-policy/content-removal-policies/submitting-content-removal-requests#github-private-information-removal-policy) Policy.
There are three types of appropriate requests to take:
[DMCA Takedown Policy](https://docs.github.com/en/site-policy/content-removal-policies/submitting-content-removal-requests#dmca-takedown-policy) (As long as the contribution is under it's own license, which it ain't according to DDNet's ToS, this ain't eligible.)
[GitHub Trademark Policy](https://docs.github.com/en/site-policy/content-removal-policies/submitting-content-removal-requests#github-trademark-policy) (All Assets with trademarks, your contribution being mentioned and your data being stored in this repository may be requested, but not the deletion of contribution in code itself. Inside your contribution, your name, data and relation with your will not be publicised.)
[GitHub Private Information Removal Policy](https://docs.github.com/en/site-policy/content-removal-policies/submitting-content-removal-requests#github-private-information-removal-policy) (Any private data provided to this repository may be deleted, as long as said data is not copyright / trademark protected, which in this case, DDNet's ToS should prevent code removal as baseline of trademark protection, since it is part of DDNet by agreement the moment the contribution was created, but like in GitHub Trademark Policy, the name, mention of contribution and licensed / trademarked Assets without connection of DDNet may be removed.)

**Comment by kaitlynia** [comment]
> I don't think there is a legal way to enforce the request of code removal, but private information, name and other trademark / copyrighted Assets made by Voxel can be deleted without conflict of the actual repository itself.

If we wanted to consider extrajudicial treatment of this request anyway, I have some thoughts on that. Here are two quotes from the license:

"Permission is granted to anyone to use this software for any purpose"

This includes maintaining versions that include the mentioned changes, or the use of these versions in servers, forks, etc.

"contact us if there is anything you want to do
that the license does not permit"

It does specifically state that we would like these requests to be communicated (though it's not really related to the license), but not necessarily that they will be honored. It's worth noting that we do not have a `CONTRIBUTING` file or otherwise some Code of Conduct for this repository, which makes it especially hard to decide what to do in cases like these.

My opinion is that this request could be honored by the maintainers, but they should also strongly consider developing a Code of Conduct or `CONTRIBUTING` file so that things are well defined and protected (like we have recently done with the map upload policy).

**Comment by MilkeeyCat** [comment]
i use rust btw

**Comment by edg-l** [comment]
https://www.zdnet.com/article/no-you-cant-take-open-source-code-back/

I dont think you can take out any code from past contributions, however you can fork it and remove it on your own repo and distribute that freely.

**Comment by fokkonaut** [comment]
I don't know which features are by you specifically, but at least the laser color change was done with my help, if it'd get removed I'd re-implement it anyways, since it's used as a feature on my server and therefore is required. Besides that, I doubt they will remove your code, and even if, you'd still be in the history and your commits could be taken by others easily.
Get better soon!

**Comment by Matodor** [comment]
VoxelRemoveCode

**Comment by def-** [comment]
Sorry to hear @VoxelDoesCode , but unfortunately we don't add/remove code based on the wishes of individuals but based on the code's merit.

**Comment by Anime-pdf** [comment]
Took you quite some time to understand all that, silly 🤓

**Comment by heinrich5991** [comment]
Any further off-topic comment will result in repercussions.
