### ISSUE TITLE
Issues with the new keyboard handling.

### ISSUE THREAD

**Issue by Jubjub** [ddnet/ddnet#819]
The new keyboard handling from a recent update makes it so that key remappings done at the OS level fail, (at least for Linux, Debian sid) for example I have mapped caps lock to escape, which no longer works, and caused my caps lock to get stuck on when closing the game.

Can there be a way to have the advantages of the raw keyboard handling + OS key remappings, or is that an inevitable casualty of ignoring keyboard layout changes?

**Comment by def-** [comment]
I don' think so. I have the same issue with caps + escape. If you can find a solution, it would be great.

**Comment by Socialdarwinist** [comment]
Do you mean with “OS level” that you have swapped the keycodes to different keysems in /usr/share/X11/xkb/keycodes, or is there another way? The mappings there are irrelevant insofar as SDL has its own tables as laid out in scripts/SDL_scancode.h.

I do not know why, but these graphical libraries always want to pass over XKB, using their own keysyms and hardcompiling compose key tables, so in GTK and Qt applications you cannot use an ~/.XCompose in addition to/usr/share/X11/locale if you do not add environment variables GTK_IM_MODULE=xim, QT_IM_MODULE=xim. Some people also add SDL_IM_MODULE=xim, but it seems to me that it does not exist. I also do not find an environment variable that could force SDL applications to use XKB keysym/keycode combination. Worse, the SDL organization itself claims that there are [no officially supported environment variables](https://wiki.libsdl.org/FAQUsingSDL#What_environment_variables_are_used_by_SDL.3F), that sounds pretty mysterious in respect to the entities responsible for them, thus I am at my wit’s end about where changes could be done. An environment variable that makes SDL applications ignore their own keysyms in favor of XKB definitions would be ideal, but apparently not to be proposed here nor in the SDL library – where, who maintains the SDL environment variables, @def? I can only find a deadland in respect to SDL environment variables, but it has potential.

**Comment by Jubjub** [comment]
In this case I'm doing the remapping through Gnome, in the `gnome-tweak-tool`. Doing a strace on it it seems it only writes to `/home/javier/.config/dconf/user` so it might be handled by the window manager? I'm really not sure, and couldn't find any real documentation on it.

Right now I'm leaning towards just implementing the "cancel/escape" action as just another regular bind, because anything beyond that would be too messy. Sure, it'd be nice for it to work automatically, but as long as all UI actions are dynamic and not hardcoded, it's not a big deal to set them once after install.

**Comment by Socialdarwinist** [comment]
We have requests for your response, @Jubjub:
* Does that bug also appear in other programs, in particular SDL2-based ones? For example 0 A.D. and Speed Dreams? Because it could point to another bug in DDNet absolving the newest implementation here if it does not happen elsewhere. Or we could find a bug completely outside of DDNet, because what I understand from your issue sounds weird.
* I am not sure what you mean with your caps lock getting stuck. Does it mean that you are permanently, until the next restart, in ALLCAPS mode after having used DDNet? Can you be content with disabling the capslock on your system? This is how you do it:
 1. Get the dconf-editor (there are other editors DE settings editors, but I use this. It’s like GnomeTweakTool for everything possible).
 2. Search the value org.gnome.libgnomekbd.keyboard.options
 3. Add the following after the last apostrophe: `, 'shift\tshift:both_capslock', 'caps\tcaps:none'`

I have disabled capslock too for months, I have not once missed it. The only justified use I have been confronted with is variable names in programming, which I do not practise. Like I have set it, you can access capslock by pressing both shift keys at the same time if you still want it sometimes.

**Comment by Jubjub** [comment]
The issue with the stuck caps locks turned out to be my fault, I thought I had set both escape and caps lock to work as escape, but turns out I had swapped them, so every time I had to press the escape key to close a dialog or dismiss the chat on DDnet, it was also toggling the caps lock status without me realizing. The main issue still stands though.

I've installed 0 A.D., and it everything worked as expected, with the caps lock key unselecting units, and I haven't had any issues with the Gnome-based remapping on any software I've used so far.

**Comment by Learath2** [comment]
Is it the correct approach to bind keys based on keycodes only? Is that how other programs do it?

**Comment by Socialdarwinist** [comment]
I have seen it yesterday in Hedgewars: “Press Z to [do whatever]”, while it actually has been Y on my German keyboard layout. Perhaps the display of keys could change according to the current keyboard layout, but else it seems legit to me to work with keycodes and ignore the actual layout in matters of functionality. In fact, probably even the displaying concession is manquée, because one can have questionable keys like dead keys or combining characters mapped to first layers of keys, and you don’t want to implement a parser for the keyboard layout and the compose tables which map doubled dead keys to their spacing equivalents. Yeah, the thoughts go far, and this is why a brutal keycode approach serves better, because of being predictable.

**Comment by Jubjub** [comment]
I think the solution for this particular problem then would be to make actions such as enter or escape that are hardcoded right now, configurable in the keyboard page.

**Comment by lilydjwg** [comment]
I have this issue too. I use xmodmap to excahnge Esc with Caps Lock. Currently it behaves like this:

* Press the Caps Lock key: nothing observed. I'm expecting it to be handled as Esc.
* Press the Esc key: the menu appears (and disappears when pressing again), and the Caps Lock LED is turned on.

I don't readlly care which key is handled as Esc in teeworlds, but the LED light is annoying :-(

**Comment by SeerLite** [comment]
Hey, I'm also having this issue with Caps Lock mapped to Escape. The game doesn't recognize it as Caps Lock at all.

Was this closed because it was fixed? Or is there some workaround for this? Thanks

**Comment by def-** [comment]
Basically we don't care about your keyboard mapping but only about the actual keys. This has the advantage of making wasd work on azerty keyboards. I think there is no way of fixing your issue without breaking other things.

**Comment by SeerLite** [comment]
Oh, I understand!
Then how about being able to remap the "go back" action (or whatever it is Escape does) in the control config? I'm sure that'd work, other games with similar keyboard handling have this option and I've been able to use Caps Lock in-game as a "go back" key.

**Comment by ncfavier** [comment]
Also having this issue. Please reopen until at least the suggested fix is implemented.

**Comment by def-** [comment]
f1, inp_translated_keys 1

**Comment by ncfavier** [comment]
Great, thanks!
