### ISSUE TITLE
`DirectInput` looks wrong

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#8408]
Message isn't flushed, so there's little point in sending it at all:

https://github.com/ddnet/ddnet/blob/1460081d8c1f7f5873ca48f94dad0c7030434fc2/src/engine/client/client.cpp#L249

**Comment by sjrc6** [comment]
If I understand this correctly this is very funny, we (not me) maintain the entire very annoying direct input system for 15 years but its only purpose of resolving same-tick fire ties by sending fire inputs faster than 50hz does not do anything because the message flush was not copied during refactor? 

https://github.com/ddnet/ddnet/blob/e56feb597bc743677633432f77513b02907fd169/src/engine/client/ec_client.cpp#L521-L534

https://github.com/ddnet/ddnet/commit/72c06a258940696093f255fb1061beb58e1cdd0b#diff-00d1dbbe357455e933c5abb5cdf5803fbfbcebc196b2ce0e242b59593cab4f86L521-L534

**Comment by sjrc6** [comment]
Although it does seem somewhat intentional as there aren't many other instances of `SendMsgEx(&Msg, 0); ` after the refactor. So I'm not sure this is actually a mistake?

**Comment by heinrich5991** [comment]
I'd say the message queue wasn't even flushed when this was introduced in 1c1677f02300e5ab10bca9c74ce7f49d4605b9d6 in 2008.

**Comment by sjrc6** [comment]
Am I crazy or is this function dead code for 15 years? I can't find any references to DirectInput anywhere in the codebase.

**Comment by heinrich5991** [comment]
Using `git log -S DirectInput`, I can confirm that this function was never called after the refactor.

**Comment by sjrc6** [comment]
I feel like I've been mandala effected. I actually remember trying to figure out why this function even exists and concluding it's important for sending fire inputs faster than the regular input loop and seeing it being called somewhere but I guess I just imagined it.

**Comment by sjrc6** [comment]
Change title to "Remove concept of direct input from code base"? Would significantly simply things if we can just put weapon code before regular tee movement code and keep the same physics without any sort of direct input concept, just process all fires from the standard input struct.

**Comment by JSaurusRex** [comment]
Wasn't direct input added for a reason? I mean for certain types of gamemodes having that faster message could definitely help, any pvp mode would probably benefit from it. I don't know about how much simpler the code is but I would say it's worth enabling it and testing to see if it has any benefits.
