### ISSUE TITLE
Masterserver should more strictly reject servers with info that is considered invalid by the client

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8541]
When refreshing the server browser, I often get debug messages like `serverbrowser_http: skipped due to info, i=54`, which means `CServerInfo2::FromJsonRaw` fails for a particular server entry. Ideally, the masterserver would already reject servers that register with invalid info so server owners can fix this.

**Comment by Learath2** [comment]
This has been my position since the start, but @heinrich5991 didn't really want to validate.

**Comment by jxsl13** [comment]
Would agree, allowing unstructured data and later trying to work with that data is a big pain point, possible but ugly.

**Comment by heinrich5991** [comment]
This is emulating the same thing as we had before we had a global list. Each server can set the info however they like. This allows mods to provide custom fields and us to add/remove stuff from the server info.

I like the current design because it makes the masterserver quite independent from our serverinfo implementation. In fact it didn't have to change due to that at all so far: https://github.com/ddnet/ddnet/commits/726e5c9a490e524bde029692764d8be36ed56b08/src/mastersrv. Just 11 commits since the start of the HTTP masterserver.

**Comment by Learath2** [comment]
Perhaps make the message more verbose and move it to a higher log level. I can see it being useful when testing.

**Comment by heinrich5991** [comment]
> as it's a pain working with unstructured data in a structured language.

It shouldn't really be that hard. Which language was that? E.g. I can think of a rather simple solution for Rust.

**Comment by heinrich5991** [comment]
Working as intended.
