### ISSUE TITLE
Shorten common server addresses

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#8712]
Currently in the server browser we are showing `tw-0.6+udp://91.232.28.130:8309,tw-0.7+udp://91.232.28.130:8309`. I think it should just be `91.232.28.130:8309`
Suggested by @Jupeyy : https://discord.com/channels/252358080522747904/293493549758939136/1272465742100566068

This started in https://github.com/ddnet/ddnet/pull/5949

**Comment by heinrich5991** [comment]
0.6-style addresses should stay like they were before the PR: `tw-0.6+udp://91.232.28.130:8309` should be `91.232.28.130:8309`.

0.7-style addresses shouldn't even make it to the server browser if the server advertises a 0.6 address.

0.7-style addresses (when they're the only ones) should get some custom prefix: `tw-0.7+udp://91.232.28.130:8309` should stay `tw-0.7+udp://91.232.28.130:8309` or get some other prefix.

**Comment by def-** [comment]
@ChillerDragon Do you want to fix this?

**Comment by ChillerDragon** [comment]
@def- I agree that hiding that would look nicer to the end user. For me personally it would be a bit annoying because that is the only way to chose and see the protocol version right now but I will be okay.

About wanting to fix it. No I do not want to do it because some reviewer will rewrite all code anyways :D. But I promised to maintain the 0.7 stuff so I guess I will give it a try anyways (https://github.com/ddnet/ddnet/pull/8716).

**Comment by ChillerDragon** [comment]
Can be closed
