### ISSUE TITLE
Inconsistent editor button/action tooltips

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#8870]
See for example screenshots in #8867.

Some of the button/action tooltips have the hotkey first while some have it last. Some hotkeys are upper case some are lower case. Some are in round and some in square brackets. I would vote for all hotkeys being lower case or with capitalized initial letters (e.g. `Ctrl+Shift+L`) and in square brackets.

Some tooltips end with a period while others do not. I think all editor tooltips should end with a period since buttons with context menus have additional text appended to the tooltip, which would only fit if the original tooltip ends with a period.

**Comment by ChillerDragon** [comment]
https://github.com/ddnet/ddnet/pull/8871 only covered the actions not all tooltips should this be reopend? Or do we just remember and gradually update when porting to quick actions or editing code around the tooltips.

Since the quick actions are a macro this style could be cleanly checked in a unit test.
