### ISSUE TITLE
Some quick actions are not double clickable

### ISSUE THREAD

**Issue by furo321** [ddnet/ddnet#8998]
Proof, server settings and envelopes are for example not double clickable. While others work fine.

https://github.com/user-attachments/assets/d06d117f-93c8-44c3-9afb-3b0d2aa6cccc

**Comment by Robyt3** [comment]
This seems to happen because the quick actions use the same UI element IDs as the original buttons. For the proof quick action you can't activate it with clicking so double clicking also does not work. But when you hover the proof quick action you can see the proof button in the menu bar becoming the hot item instead.

**Comment by ChillerDragon** [comment]
I think you suggested to share the element IDs @Robyt3 whats the plan here? Revert the sharing? And give the buttons their static variables back?
