### ISSUE TITLE
IPs visible for moderators in rcon console

### ISSUE THREAD

**Issue by 12pm** [ddnet/ddnet#907]
> Since ip addresses are considered sensitive / confidential information it's reasonable to hide them from non-administrators (moderators in our case).

The rcon commands ``mutes``, ``unmute``, ``bans`` and ``unban`` still display IPs if you are logged in as a moderator, thus can be abused to get someones IP.

**Comment by Learath2** [comment]
Maybe we should just let mods see the ip's.

**Comment by heinrich5991** [comment]
> Maybe we should just let mods see the ip's.

Not just out of laziness. :)

**Comment by Ryozuki** [comment]
Maybe what @Learath2 said is true, actually the mute system works with "mute indexes" so hiding the IP would make the moderator don't know who is who when using "mutes" to "unmute" someone. And also bans works with IPs not ids. So if a mod bans someone by mistake, without the ip he/she can't unban it.

**Comment by andrija1213** [comment]
What would you use then? If it's necessary, you can hash the IP address and compare hashes then. It should work as good as just addresses and moderators or even admins won't be able to see them :P

**Comment by Learath2** [comment]
What would we use instead of IPs? I'd just use IPs. The input pool of IP addresses is small enough that a hash is merely an inconvenience to someone with malicious intent. Even with salt 4,294,967,296 values are just not that hard to hash. An intentionally slow hashing algorithm like bcrypt or PBKDF2 might help in that aspect.

But the point is why even bother? Server owners/admins have actual physical access to the server they could modify the binary or just get a tcpdump.

I don't really see the issue here with moderators seeing IPs. If they are going to abuse it they shouldn't be mods in the first place. The only valid point I see is accidental leakage which we can fix with having a separate (or an argument to the) status/bans commands to only output IP if requested.

**Comment by 12pm** [comment]
Agree, your proposal should be fine. AFAIK no mod abused the bug since this issue was opened :D

**Comment by andrija1213** [comment]
IP addresses are the only logical solution, and I think that strong hashes like MD5 would be more than an "inconvenience" :^). Of course, it's breakable, but as you said, it doesn't really matter. Trying so hard to get an IP address of a player in a puffle game just to get blocked out by router's firewall is plain stupid... Player's who aren't technologically illiterate probably already have some sort of defence or don't have vurneable points open, those who are are probably protected by consumer-grade software(implying Windows or similar) so it should all be good.

**Comment by heinrich5991** [comment]
@andrija1213 You can't prevent your connection from being DDoSed by someone who learns your IP address. No "consumer-grade software" helps against that.

**Comment by Learath2** [comment]
MD5 is really not a strong hash in this case. You can do way more then the
4 billion required hashes in less then half a minute on a half decent gpu
or cpu.

The attack itself though due to the nature of teeworlds protocol isn't
actually harmless. With the IP of a player you can spoof their packets to
other servers to hijack rcon sessions or kill them or drop them

But still if this is being abused you have some bad moderators. If a server
owner is letting mods abuse it then there is nothing you can do in the
first place.

**Comment by heinrich5991** [comment]
The problem is accidental leaking. Showing IP addresses should not be the default – in fact, e.g. the forum software Discourse only shows them after a click. The problem is accidental leakage, as happened when the pull request was opened. This had *nothing* to do with bad moderators or moderator abuse.

**Comment by Learath2** [comment]
Exactly so we should devise a fix that doesn't add too many new commands
and doesn't change the code too much :)

**Comment by andrija1213** [comment]
I guess I overlooked manipulation in-game.
@heinrich5991 Although DDOS could be a problem for non "tech savvy"(https://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2015/12/anonymous-1200x779.jpg), most modern routers have DDOS prevention mechanisms built-in, or am I wrong? Correct me if I am. My "Windows" part makes no sense though, I wanted to mention routers mostly but eh, Windows has a firewall too I guess.

**Comment by 12pm** [comment]
fixed by 25c54ef4dbe8255776ef79da294c22090a3d2d34
