### ISSUE TITLE
Autojoining with password

### ISSUE THREAD

**Issue by trikiman** [ddnet/ddnet#9201]
if u already have correct password, u will autojoin and u dont need to press "try again" button
![image](https://github.com/user-attachments/assets/b195affc-47e6-42e8-b60b-4b0c777d6f4f)

**Comment by SollyBunny** [comment]
How will the server know you have the correct password. Sending it over and over again would lead to rate limiting and otherwise the ability to brute force it. The server could send the password length and only send it when it reaches that length like how many 2 auth prompts work but would make smaller passwords even less secure to dictionary attacks etc

**Comment by trikiman** [comment]
> Sending it over and over again
no, need only one time if password not empty.

**Comment by trikiman** [comment]
>  Sending it over and over again 

no, need only one time if password not empty.

**Comment by SollyBunny** [comment]
Ah, my bad. I thought you meant if you hand't already put in the password. Yeah I think this is a intended feature which doesn't work since it says "Password Incorrect"

**Comment by SollyBunny** [comment]
There's only 1 place for a remembered password to be stored (password in f1), so it's probably like this to prevent servers from getting access to passwords when you try to connect to them

**Comment by trikiman** [comment]
On one side, I'm happy something is completed, but on the other side, this is not really important. For example, #8528 saves a lot more time because people use the editor more than pass.

It's just interesting how orders work; it looks like old issues were never approved.
