### ISSUE TITLE
cant play (version 18.8.1/18.8, OS windows10 32-bit)

### ISSUE THREAD

**Issue by tw-user121** [ddnet/ddnet#9411]
my game goes crazy and it wont let me join any of my friends 

https://github.com/user-attachments/assets/d6f5da6f-bf36-4a90-81ef-6676da548129

im was useing 18.7 and it worked but when i updated it to 18.8 or 18.8.1 it didnt work
im useing windows 10 32-bit (OS) and this is the first hapening and i dont know what could have did this

**Comment by BlaiZephyr** [comment]
please try and use Discord or our IRC bridge for questions like these.

IRC: #ddnet on Quakenet |
Matrix: #ddnet-developer:matrix.org
Discord: https://discord.gg/8sqh3CPy

but since you already created this, please give us more information:

please try these steps before continuing: https://wiki.ddnet.org/wiki/GFX_Troubleshooting
also check if your drivers require an update.

if these steps didnt help and you're unable to access discord/IRC, please provide us with this information:


your Operating System
your GPU & CPU
did this happen before?
was it working without problems before?
do you remember what you did that caused this?

**Comment by def-** [comment]
Try DDNet 18.8.2

**Comment by Jupeyy** [comment]
nod on discord confirmed that it works
