### ISSUE TITLE
Automatically determine when OpenGL 3 is better

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#980]
Can we detect the GPU capabilities to see that it supports native OpenGL 3 and only enable it in that case?

**Comment by def-** [comment]
@Jupeyy Any ideas?

**Comment by def-** [comment]
I want to get this into the next release soon. I see there is a glewIsSupported, but wouldn't that just tell me that OpenGL 3.3 is supported while the driver is simulating it on really old GPUs?

**Comment by Jupeyy** [comment]
mhh, i don't think this is really possible, I can't remember ever read to check, if something is hardware rendered or software rendered.
Also i dont think Opengl 3 is ever worse, except the streaming buffer issue i mentioned. And for that i dont find a fix, khronos itself says something like "use more buffers"
https://www.khronos.org/opengl/wiki/Buffer_Object_Streaming#Explicit_multiple_buffering

but that just isnt the same thing like in old opengl version/api the pointers to a System memory location instead of setting up VRAM.
I'm a bit sorry, that this makes the client very bad performing, especially if the buffer is used many times(chatting etc.). I also didnt knew that, since I never before streaming everything every frame.

**Comment by def-** [comment]
I see, you are right. On another 10 year old gpu with a more reasonable driver opengl3 works fine.
