### ISSUE TITLE
OpenGL turns tw into 4k

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#987]
so, as soon as you have open gl 3 activated the map will have a high resolution. especially the unhook and freeze combination is ugly because there are big gaps inbetween them then.

**Comment by Jupeyy** [comment]
screens maybe?
it just doesnt need the border fix, since it draws everything fine.

the mipmap level is also different and looks like you turn on "prefer quality" in you nvidia settings

**Comment by fokkonaut** [comment]
![ddnet exe_screenshot_2018 01 14_-_18 01 33 08](https://user-images.githubusercontent.com/35420825/34920337-8f753dfa-f971-11e7-8a91-476d7e90fa58.png)

**Comment by fokkonaut** [comment]
![ddnet exe_screenshot_2018 01 14_-_18 01 33 08](https://user-images.githubusercontent.com/35420825/34920348-a6a51950-f971-11e7-85c5-49c7af8f643c.png)
open gl 3 = 0

**Comment by fokkonaut** [comment]
![ddnet exe_screenshot_2018 01 14_-_18 02 01 93](https://user-images.githubusercontent.com/35420825/34920360-c78e837c-f971-11e7-81e7-49854d68e414.png)

**Comment by fokkonaut** [comment]
ae you can clearly see that open gl 3 turns on high resolution and if there is a possiility to let the graphics like they are but use gl3 for zooning out. I dont want this high resolution just bcs gl3 is on

**Comment by Jupeyy** [comment]
but srsly. the opengl 3 off looks worse, because it clearly removes parts off the border,there are gaps, because the tileset was made like that.

Teeworlds 0.7 does something similar(just another technique)

i cannot simple remove that feature again, i implemented it because tile images are bleeding else.
If you go into higher resolution there is no higher mipmap level anymore, and the old mipmap offset calculation works pretty much for 2k.

here i scaled a HD ready screenshot to an 2k screenshot(both without Opengl 3):
so if you ask me it even is a bug, if it just removes part of the actually image

![screenshot_2018-01-15_07-06-50](https://user-images.githubusercontent.com/6654924/34929252-f4fb5f0a-f9c2-11e7-85ed-f6bb87abd386.png)

also this doesnt have todo with the "higher resolution", the bluring only occurs on old opengl, because nvidia for example uses different mipmap calculation i cant use because of texture bleeding for the tile images. You might not understand what i am talking about but imagine it like this:
the old client makes a calculation how the image is scaled for different zoom steps(and switching the resolution is basically a zooming), it then adjust the image so you get the coordinates for 1 tile from the tile images(grass_main or stuff like that). But the old client only makes this by a specific algorithm(the graphic card may not use this algorith, and if they don't met either parts of the image are removed, or even worse: you see parts of the tile that is next to the tile that is rendered(i think you can test this by zooming into unhook tiles alot, you see a red line that comes from the Kill tile)).
Instead of that now i use the algorithm that the OpenGL spec suggests for mipmap calculation and send that mipmap level to the GPU.

**Comment by def-** [comment]
Sounds like "not a bug". I'm ok with the new behaviour.

**Comment by fokkonaut** [comment]
can i get the old blurry textures myself again?

**Comment by Jupeyy** [comment]
For your entities you could simply edit the tileset image.
Else you can try edit the shaders and add a trilinear filter yourself. Else you can just set the offset manually in the shaders so your standard zoom looks fine and only the zoom in zoom out suffers from bleeding

for the last option
in the vertex shaders you find a variable called `LOD` replace it with your own variable and set your own from 0-5, whatever mipmap level you prefer :)

**Comment by fokkonaut** [comment]
i will try out the last option or can you give me indtructions for the other method?

**Comment by Jupeyy** [comment]
/data/shader

there is no default value.
0 means it loads the actual non modified tile image 1024*1024
1 means 512*512
2 256*256
...

You will need to modify the .vert files that have a variable called LOD.
You can then create a local variable at the beggining of the main function (e.g. ownLOD) and set it to your value and replace all occuriencies of LOD with ownLOD

**Comment by fokkonaut** [comment]
complicated af, you got discord?

**Comment by Jupeyy** [comment]
I do, but you won't be able to add me.

What don't you understand? just look for LOD in the .vert files make an local variable from 0-5 and look what looks best for you.

**Comment by fokkonaut** [comment]
could you send me the edited vert files? im rly dumb ._.

**Comment by Jupeyy** [comment]
nope, i wont give support for such things
